<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { KeyRound, Save, UserRound } from '@lucide/vue'
import { get, put } from '../api'
import { useAppStore } from '../stores/app'
const store=useAppStore();const user=ref<any>(null);const username=reactive({current_password:'',new_username:''});const password=reactive({current_password:'',new_password:'',confirm_password:''});const saving=ref('')
async function load(){try{user.value=await get('/admin/api/account.php');username.new_username=user.value.username||''}catch(e:any){store.notify(e?.message||'账户加载失败','error')}}
async function changeUsername(){if(user.value?.username_locked)return;if(!username.new_username.trim())return store.notify('请填写新用户名','error');if(!username.current_password)return store.notify('请输入当前密码以验证身份','error');saving.value='username';try{const r:any=await put('/admin/api/account.php',{action:'username',...username,new_username:username.new_username.trim()});store.notify(r.message||'用户名已修改');username.current_password='';await load();await store.bootstrap()}catch(e:any){store.notify(e?.message||'修改失败','error')}finally{saving.value=''}}
async function changePassword(){if(!password.current_password)return store.notify('请输入当前密码','error');if(password.new_password.length<8)return store.notify('新密码长度不能少于 8 位','error');if(password.new_password!==password.confirm_password)return store.notify('两次输入的新密码不一致','error');saving.value='password';try{const r:any=await put('/admin/api/account.php',{action:'password',...password});store.notify(r.message||'密码已修改');Object.assign(password,{current_password:'',new_password:'',confirm_password:''})}catch(e:any){store.notify(e?.message||'修改失败','error')}finally{saving.value=''}}
onMounted(load)
</script>
<template><div>
<div class="page-head"><div><h1>账户管理</h1><p>管理当前后台账户与登录安全；修改密码后其他旧 Session 会立即失效。</p></div></div>
<div class="two-col">
 <section class="form-card"><div class="panel-head"><div><h3><UserRound :size="13" style="display:inline;vertical-align:-2px;margin-right:5px"/>账户信息</h3><span v-if="user">创建于 {{user.created_at||'—'}} · 最近登录 {{user.last_login||'从未登录'}}</span></div></div><div class="form-section"><div class="field"><label>用户名</label><input v-model="username.new_username" class="input" :disabled="!!user?.username_locked"><small v-if="user?.username_locked">SaaS 租户 slug 同时是公开 URL，只能由超级管理员做迁移。</small></div><div v-if="!user?.username_locked" class="field" style="margin-top:10px"><label>当前密码</label><input v-model="username.current_password" type="password" class="input" autocomplete="current-password" placeholder="用于验证身份"></div><button v-if="!user?.username_locked" class="button primary" style="margin-top:12px" :disabled="saving==='username'" @click="changeUsername"><Save :size="13"/>{{saving==='username'?'保存中…':'修改用户名'}}</button></div></section>
 <section class="form-card"><div class="panel-head"><div><h3><KeyRound :size="13" style="display:inline;vertical-align:-2px;margin-right:5px"/>修改密码</h3><span>至少 8 位</span></div></div><div class="form-section"><div class="field"><label>当前密码</label><input v-model="password.current_password" type="password" class="input" autocomplete="current-password"></div><div class="field" style="margin-top:10px"><label>新密码</label><input v-model="password.new_password" type="password" minlength="8" class="input" autocomplete="new-password"></div><div class="field" style="margin-top:10px"><label>再次输入新密码</label><input v-model="password.confirm_password" type="password" minlength="8" class="input" autocomplete="new-password"></div><button class="button primary" style="margin-top:12px" :disabled="saving==='password'" @click="changePassword"><KeyRound :size="13"/>{{saving==='password'?'修改中…':'修改密码'}}</button></div></section>
</div>
</div></template>
