<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { ArrowDown, ArrowUp, ExternalLink, Images, Plus, RefreshCw, Search, Trash2, Upload, X } from '@lucide/vue'
import { useRouter } from 'vue-router'
import { del, get, post, put } from '../api'
import { useAppStore } from '../stores/app'

type AppRow = Record<string, any>
type Tab = 'basic'|'ios'|'mobileconfig'|'android'|'downloads'|'images'
const store=useAppStore();const router=useRouter();const apps=ref<AppRow[]>([]);const loading=ref(false);const search=ref('');const drawer=ref(false);const drawerTab=ref<Tab>('basic');const saving=ref(false)
const editing=reactive<AppRow>({});const downloads=ref<AppRow[]>([]);const images=ref<AppRow[]>([]);const featureCategories=ref<any[]>([]);const attachments=ref<any[]>([]);const mobileconfigs=ref<any[]>([])
const newDownload=reactive({btn_type:'android',btn_icon:'fab fa-android',btn_text:'Android',btn_subtext:'下载安装',href:'#'});const newImage=reactive({image_url:'',alt_text:''})
const typeOptions=[['android','Android 直接下载'],['android-install','Android 安装页'],['ios-ipa','iOS IPA 直接安装'],['ios-ipa-install','iOS IPA 安装页'],['ios-mobileconfig','Mobileconfig 直接下载'],['ios-mobileconfig-install','Mobileconfig 安装页'],['ios','iOS 通用'],['windows','Windows'],['web','Web'],['tv','TV'],['other','其他']]
const iconMap:Record<string,string>={android:'fab fa-android','android-install':'fab fa-android','ios-ipa':'fab fa-apple','ios-ipa-install':'fab fa-apple','ios-mobileconfig':'fab fa-apple','ios-mobileconfig-install':'fab fa-apple',ios:'fab fa-apple',windows:'fab fa-windows',web:'fas fa-globe',tv:'fas fa-tv',other:'fas fa-download'}
const filtered=computed(()=>{const q=search.value.trim().toLowerCase();return apps.value.filter(a=>!q||`${a.name} ${a.slug} ${a.ios_bundle_id||''}`.toLowerCase().includes(q))})
const appOrigin=computed(()=>location.origin);const plistInstall=computed(()=>editing.slug&&editing.ios_ipa_url?`itms-services://?action=download-manifest&url=${encodeURIComponent(location.origin+'/api/plist.php?app='+editing.slug)}`:'');const mcInstall=computed(()=>editing.slug?`${location.origin}/api/mobileconfig.php?app=${editing.slug}`:'');const androidInstall=computed(()=>editing.slug?`${location.origin}/android/?app=${editing.slug}`:'')
function assetUrl(v:string){if(!v)return '';return /^(https?:)?\/\//i.test(v)||v.startsWith('/')?v:`/${v}`}
function resetEditing(){Object.keys(editing).forEach(k=>delete editing[k]);Object.assign(editing,{id:0,slug:'',name:'',icon:'fas fa-mobile-alt',icon_url:'',theme_color:'#4f46e5',is_active:1,feature_category_id:0,ios_version:'',ios_ipa_url:'',ios_plist_url:'',ios_bundle_id:'',ios_cert_name:'',ios_size:'',ios_description:'',ios_template:'modern',mc_file_id:null,mc_file_url:'',mc_description:'',mc_template:'modern',android_version:'',android_apk_url:'',android_size:'',android_description:'',android_template:'modern'})}
async function load(){loading.value=true;try{apps.value=await get('/admin/api/apps.php')}catch(e:any){store.notify(e?.message||'应用列表加载失败','error')}finally{loading.value=false}}
async function loadRelated(id:number){
  const jobs:Promise<any>[]=[get('/admin/api/features.php?action=categories'),get(`/admin/api/attachments.php?app_id=${id}`),get('/admin/api/mobileconfig.php?action=list')]
  try{const [cats,atts,mcs]=await Promise.all(jobs);featureCategories.value=cats;attachments.value=atts;mobileconfigs.value=mcs}catch(e:any){store.notify(e?.message||'应用关联数据加载失败','error')}
}
async function openApp(app?:AppRow){drawerTab.value='basic';resetEditing();downloads.value=[];images.value=[];featureCategories.value=[];attachments.value=[];mobileconfigs.value=[]
  try{featureCategories.value=await get('/admin/api/features.php?action=categories');if(app?.id){const detail=await get<AppRow>(`/admin/api/apps.php?id=${encodeURIComponent(app.id)}`);Object.assign(editing,detail);downloads.value=detail.downloads||[];images.value=detail.images||[];await loadRelated(Number(app.id))}}catch(e:any){store.notify(e?.message||'应用详情加载失败','error');return}drawer.value=true}
function appPayload(){return {id:Number(editing.id),name:editing.name||'',icon:editing.icon||'',icon_url:editing.icon_url||'',theme_color:editing.theme_color||'#007AFF',is_active:Number(editing.is_active)?1:0,feature_category_id:Number(editing.feature_category_id||0),ios_ipa_url:editing.ios_ipa_url||'',ios_plist_url:editing.ios_ipa_url?plistInstall.value:'',ios_bundle_id:editing.ios_bundle_id||'',ios_cert_name:editing.ios_cert_name||'',ios_version:editing.ios_version||'',ios_size:editing.ios_size||'',ios_description:editing.ios_description||'',ios_template:editing.ios_template||'modern',mc_file_id:editing.mc_file_id?Number(editing.mc_file_id):null,mc_file_url:editing.mc_file_url||'',mc_description:editing.mc_description||'',mc_template:editing.mc_template||'modern',android_apk_url:editing.android_apk_url||'',android_version:editing.android_version||'',android_size:editing.android_size||'',android_description:editing.android_description||'',android_template:editing.android_template||'modern'}}
async function saveApp(close=true){if(!editing.name?.trim())return store.notify('应用名称不能为空','error');saving.value=true;try{if(!editing.id){if(!editing.slug?.trim())return store.notify('新应用必须填写标识 slug','error');const r:any=await post('/admin/api/apps.php',{slug:editing.slug,name:editing.name,icon:editing.icon,icon_url:editing.icon_url,theme_color:editing.theme_color});editing.id=Number(r.id);await loadRelated(Number(editing.id))}await put('/admin/api/apps.php',appPayload());store.notify('应用配置已保存');await load();if(close)drawer.value=false}catch(e:any){store.notify(e?.message||'保存失败','error')}finally{saving.value=false}}
async function removeApp(){if(!editing.id||!confirm(`永久删除「${editing.name}」及其关联文件？`))return;try{await del('/admin/api/apps.php',{id:editing.id});drawer.value=false;await load();store.notify('应用已删除')}catch(e:any){store.notify(e?.message||'删除失败','error')}}
async function uploadTo(target:any,key:string,file?:File){if(!file)return;const fd=new FormData();fd.append('category','image');fd.append('file',file);try{const r:any=await post('/admin/api/upload.php',fd);target[key]=r.url||'';store.notify('图片已上传')}catch(e:any){store.notify(e?.message||'上传失败','error')}}
function flattenAttachments(){const out:any[]=[];attachments.value.forEach(p=>(p.files||[]).forEach((f:any)=>out.push({...f,platform_name:p.name})));return out}
function chooseAttachment(field:string,event:Event){const v=(event.target as HTMLSelectElement).value;if(v)editing[field]=v}
function chooseMc(){const m=mobileconfigs.value.find(x=>Number(x.id)===Number(editing.mc_file_id));if(m)editing.mc_file_url=m.file_path||''}
function autoDownload(d:any){d.btn_icon=iconMap[d.btn_type]||'fas fa-download';const slug=editing.slug||'';if(!slug)return;const map:Record<string,string>={'android-install':`/android/?app=${slug}`,'ios-ipa':plistInstall.value,'ios-ipa-install':`/ios/?app=${slug}`,'ios-mobileconfig':`/api/mobileconfig.php?app=${slug}`,'ios-mobileconfig-install':`/ios/?app=${slug}&type=mobileconfig`};if(map[d.btn_type])d.href=map[d.btn_type]}
async function addDownload(){if(!editing.id)return store.notify('请先保存应用','error');try{await post('/admin/api/downloads.php',{app_id:editing.id,...newDownload});downloads.value=await get(`/admin/api/downloads.php?app_id=${editing.id}`);store.notify('下载方式已添加')}catch(e:any){store.notify(e?.message||'添加失败','error')}}
async function saveDownload(d:any){try{await put('/admin/api/downloads.php',{...d,is_active:Number(d.is_active??1)?1:0});store.notify('下载方式已保存')}catch(e:any){store.notify(e?.message||'保存失败','error')}}
async function removeDownload(d:any){if(!confirm('删除这个下载方式？'))return;try{await del('/admin/api/downloads.php',{id:d.id});downloads.value=downloads.value.filter(x=>x.id!==d.id);store.notify('已删除')}catch(e:any){store.notify(e?.message||'删除失败','error')}}
async function move(list:any[],i:number,delta:number,table:string){const n=i+delta;if(n<0||n>=list.length)return;const copy=[...list];const [x]=copy.splice(i,1);copy.splice(n,0,x);try{await post('/admin/api/reorder.php',{table,order:copy.map(x=>Number(x.id))});if(table==='apps')apps.value=copy;else if(table==='app_downloads')downloads.value=copy;else images.value=copy;store.notify('排序已保存')}catch(e:any){store.notify(e?.message||'排序失败','error')}}
async function addImage(){if(!editing.id||!newImage.image_url)return store.notify('请先选择图片','error');try{await post('/admin/api/images.php',{app_id:editing.id,...newImage});images.value=await get(`/admin/api/images.php?app_id=${editing.id}`);Object.assign(newImage,{image_url:'',alt_text:''});store.notify('截图已添加')}catch(e:any){store.notify(e?.message||'添加失败','error')}}
async function saveImage(img:any){try{await put('/admin/api/images.php',{id:img.id,image_url:img.image_url,alt_text:img.alt_text||''});store.notify('截图信息已保存')}catch(e:any){store.notify(e?.message||'保存失败','error')}}
async function removeImage(img:any){if(!confirm('删除这张截图及其上传文件？'))return;try{await del('/admin/api/images.php',{id:img.id});images.value=images.value.filter(x=>x.id!==img.id);store.notify('截图已删除')}catch(e:any){store.notify(e?.message||'删除失败','error')}}
onMounted(load)
</script>

<template><div>
<div class="page-head"><div><h1>应用管理</h1><p>完整维护应用身份、iOS OTA、Mobileconfig、Android 安装页、下载按钮与截图。</p></div><div class="page-actions"><button class="button" @click="load"><RefreshCw :size="14"/>刷新</button><button class="button" @click="router.push('/media')"><Images :size="14"/>媒体库</button><button class="button primary" @click="openApp()"><Plus :size="14"/>添加应用</button></div></div>
<div class="toolbar"><div class="search-box"><Search :size="15"/><input v-model="search" class="input" placeholder="搜索名称、slug 或 Bundle ID…"></div><span class="subtle">{{filtered.length}} 个应用</span></div>
<div v-if="loading" class="app-list"><div v-for="i in 3" :key="i" class="app-row"><div class="skeleton" style="height:46px;width:220px"></div></div></div>
<div v-else-if="filtered.length" class="app-list"><div v-for="(a,i) in filtered" :key="a.id" class="app-row"><div class="app-main"><div class="app-icon"><img v-if="a.icon_url" :src="assetUrl(a.icon_url)" alt=""><span v-else>{{String(a.name||'A').slice(0,1)}}</span></div><div class="app-copy"><b>{{a.name}}</b><code>{{a.slug}}</code></div></div><div class="app-info"><div class="info"><span>iOS</span><b>{{a.ios_version||'—'}}</b></div><div class="info"><span>Android</span><b>{{a.android_version||'—'}}</b></div><div class="info"><span>内容</span><b>{{a.dl_count||0}} 下载 · {{a.img_count||0}} 图</b></div></div><div class="row-actions"><button class="icon-button" @click="move(apps,apps.findIndex(x=>x.id===a.id),-1,'apps')"><ArrowUp :size="13"/></button><button class="icon-button" @click="move(apps,apps.findIndex(x=>x.id===a.id),1,'apps')"><ArrowDown :size="13"/></button><span class="badge" :class="{muted:!Number(a.is_active)}">{{Number(a.is_active)?'已发布':'已隐藏'}}</span><button class="button small" @click="openApp(a)">编辑</button></div></div></div>
<div v-else class="empty-state"><b>没有找到应用</b>修改搜索条件，或新建第一个应用。</div>

<div v-if="drawer" class="drawer-mask" @click.self="drawer=false"><aside class="drawer" style="max-width:900px"><div class="drawer-head"><div><b>{{editing.id?'编辑应用':'新建应用'}}</b><span class="subtle" style="display:block;margin-top:3px">{{editing.slug||'尚未创建'}}</span></div><button class="icon-button" @click="drawer=false"><X :size="15"/></button></div><div class="drawer-body">
<div class="drawer-tabs"><button v-for="t in [{k:'basic',n:'基础'},{k:'ios',n:'iOS OTA'},{k:'mobileconfig',n:'Mobileconfig'},{k:'android',n:'Android'},{k:'downloads',n:'下载方式'},{k:'images',n:'截图'}]" :key="t.k" :class="{active:drawerTab===t.k}" @click="drawerTab=t.k as Tab">{{t.n}}</button></div>

<div v-if="drawerTab==='basic'" class="form-card"><div class="form-section"><h3>基础信息</h3><div class="form-grid"><div class="field"><label>应用名称</label><input v-model="editing.name" class="input"></div><div class="field"><label>标识 slug</label><input v-model="editing.slug" class="input" :disabled="!!editing.id"><small>创建后保持稳定。</small></div><div class="field"><label>FA 图标</label><input v-model="editing.icon" class="input"></div><div class="field"><label>图片图标 URL</label><div class="toolbar"><input v-model="editing.icon_url" class="input"><label class="button small"><Upload :size="12"/>上传<input type="file" accept="image/*" hidden @change="uploadTo(editing,'icon_url',($event.target as HTMLInputElement).files?.[0])"></label></div></div><div class="field"><label>主题色</label><input v-model="editing.theme_color" type="color" class="input" style="padding:4px"></div><div class="field"><label>公开状态</label><select v-model.number="editing.is_active" class="select"><option :value="1">已发布</option><option :value="0">隐藏</option></select></div><div class="field full"><label>特色卡片分类</label><select v-model.number="editing.feature_category_id" class="select"><option :value="0">使用全局 / 未分类卡片</option><option v-for="c in featureCategories" :key="c.id" :value="Number(c.id)">{{c.name}}</option></select></div></div></div></div>

<div v-if="drawerTab==='ios'" class="form-card"><div class="form-section"><h3>iOS OTA / Plist</h3><p>保存 IPA 后自动维护 itms-services 安装链接。</p><div class="form-grid"><div class="field full"><label>IPA 文件地址</label><input v-model="editing.ios_ipa_url" class="input"><select class="select" style="margin-top:6px" @change="chooseAttachment('ios_ipa_url',$event)"><option value="">从附件选择…</option><option v-for="f in flattenAttachments()" :key="f.id" :value="f.file_url">{{f.platform_name}} · {{f.version}} · {{f.file_size}}</option></select></div><div class="field"><label>Bundle ID</label><input v-model="editing.ios_bundle_id" class="input"></div><div class="field"><label>证书名称</label><input v-model="editing.ios_cert_name" class="input"></div><div class="field"><label>版本</label><input v-model="editing.ios_version" class="input"></div><div class="field"><label>大小</label><input v-model="editing.ios_size" class="input"></div><div class="field"><label>安装页模板</label><select v-model="editing.ios_template" class="select"><option value="modern">现代毛玻璃</option><option value="classic">经典 App Store</option></select></div><div class="field full"><label>应用简介</label><textarea v-model="editing.ios_description" class="textarea"></textarea></div><div class="field full"><label>Plist 安装链接</label><code style="display:block;word-break:break-all">{{plistInstall||'填写 IPA 后自动生成'}}</code></div></div></div></div>

<div v-if="drawerTab==='mobileconfig'" class="form-card"><div class="form-section"><h3>Mobileconfig 安装配置</h3><p>可绑定“Mobileconfig”页面生成的文件，也可以直接填写附件或 URL。</p><div class="form-grid"><div class="field"><label>已生成文件</label><select v-model.number="editing.mc_file_id" class="select" @change="chooseMc"><option :value="null">不绑定生成记录</option><option v-for="m in mobileconfigs" :key="m.id" :value="Number(m.id)">{{m.display_name||('Mobileconfig #'+m.id)}}</option></select></div><div class="field"><label>安装页模板</label><select v-model="editing.mc_template" class="select"><option value="modern">现代毛玻璃</option><option value="classic">经典 App Store</option></select></div><div class="field full"><label>Mobileconfig 文件 URL</label><input v-model="editing.mc_file_url" class="input"><select class="select" style="margin-top:6px" @change="chooseAttachment('mc_file_url',$event)"><option value="">从附件选择…</option><option v-for="f in flattenAttachments()" :key="f.id" :value="f.file_url">{{f.platform_name}} · {{f.version}} · {{f.file_size}}</option></select></div><div class="field full"><label>应用简介</label><textarea v-model="editing.mc_description" class="textarea"></textarea></div><div class="field full"><label>公开下载链接</label><code style="display:block;word-break:break-all">{{mcInstall}}</code></div></div></div></div>

<div v-if="drawerTab==='android'" class="form-card"><div class="form-section"><h3>Android 安装页</h3><div class="form-grid"><div class="field full"><label>APK 文件地址</label><input v-model="editing.android_apk_url" class="input"><select class="select" style="margin-top:6px" @change="chooseAttachment('android_apk_url',$event)"><option value="">从附件选择…</option><option v-for="f in flattenAttachments()" :key="f.id" :value="f.file_url">{{f.platform_name}} · {{f.version}} · {{f.file_size}}</option></select></div><div class="field"><label>版本</label><input v-model="editing.android_version" class="input"></div><div class="field"><label>大小</label><input v-model="editing.android_size" class="input"></div><div class="field"><label>安装页模板</label><select v-model="editing.android_template" class="select"><option value="modern">现代风格</option><option value="classic">经典 Play Store</option></select></div><div class="field full"><label>应用简介</label><textarea v-model="editing.android_description" class="textarea"></textarea></div><div class="field full"><label>安装页链接</label><code>{{androidInstall}}</code></div></div></div></div>

<div v-if="drawerTab==='downloads'"><div v-if="!editing.id" class="empty-state">请先保存应用，再添加下载方式。</div><template v-else><div class="form-card"><div class="form-section"><h3>添加下载方式</h3><div class="form-grid"><div class="field"><label>类型</label><select v-model="newDownload.btn_type" class="select" @change="autoDownload(newDownload)"><option v-for="t in typeOptions" :key="t[0]" :value="t[0]">{{t[1]}}</option></select></div><div class="field"><label>按钮文字</label><input v-model="newDownload.btn_text" class="input"></div><div class="field"><label>副标题</label><input v-model="newDownload.btn_subtext" class="input"></div><div class="field"><label>图标类</label><input v-model="newDownload.btn_icon" class="input"></div><div class="field full"><label>链接</label><input v-model="newDownload.href" class="input"></div></div><button class="button primary" style="margin-top:10px" @click="addDownload"><Plus :size="13"/>添加</button></div></div><div class="task-list" style="margin-top:10px"><div v-for="(d,i) in downloads" :key="d.id" class="task-card"><div class="task-head"><b>{{d.btn_text||d.btn_type}}</b><div class="page-actions"><button class="icon-button" @click="move(downloads,i,-1,'app_downloads')"><ArrowUp :size="13"/></button><button class="icon-button" @click="move(downloads,i,1,'app_downloads')"><ArrowDown :size="13"/></button></div></div><div class="form-grid" style="margin-top:8px"><div class="field"><label>类型</label><select v-model="d.btn_type" class="select" @change="autoDownload(d)"><option v-for="t in typeOptions" :key="t[0]" :value="t[0]">{{t[1]}}</option></select></div><div class="field"><label>状态</label><select v-model.number="d.is_active" class="select"><option :value="1">启用</option><option :value="0">停用</option></select></div><div class="field"><label>文字</label><input v-model="d.btn_text" class="input"></div><div class="field"><label>副标题</label><input v-model="d.btn_subtext" class="input"></div><div class="field"><label>图标</label><input v-model="d.btn_icon" class="input"></div><div class="field full"><label>链接</label><input v-model="d.href" class="input"></div></div><div class="page-actions" style="margin-top:9px"><button class="button small" @click="saveDownload(d)">保存</button><button class="button small danger" @click="removeDownload(d)"><Trash2 :size="12"/>删除</button></div></div></div></template></div>

<div v-if="drawerTab==='images'"><div v-if="!editing.id" class="empty-state">请先保存应用，再添加截图。</div><template v-else><div class="form-card"><div class="form-section"><h3>添加截图</h3><div class="field"><label>图片 URL</label><input v-model="newImage.image_url" class="input"></div><div class="field" style="margin-top:8px"><label>描述</label><input v-model="newImage.alt_text" class="input"></div><div class="page-actions" style="margin-top:9px"><label class="button"><Upload :size="13"/>上传<input type="file" accept="image/*" hidden @change="uploadTo(newImage,'image_url',($event.target as HTMLInputElement).files?.[0])"></label><button class="button" @click="router.push('/media')"><Images :size="13"/>媒体库</button><button class="button primary" @click="addImage"><Plus :size="13"/>添加截图</button></div></div></div><div class="task-list" style="margin-top:10px"><article v-for="(img,i) in images" :key="img.id" class="task-card"><img :src="assetUrl(img.image_url)" :alt="img.alt_text||''" style="width:100%;height:180px;object-fit:contain;background:var(--surface-2);border-radius:9px"><div class="form-grid" style="margin-top:8px"><div class="field"><label>图片 URL</label><input v-model="img.image_url" class="input"></div><div class="field"><label>描述</label><input v-model="img.alt_text" class="input"></div></div><div class="page-actions" style="margin-top:9px"><button class="icon-button" @click="move(images,i,-1,'app_images')"><ArrowUp :size="13"/></button><button class="icon-button" @click="move(images,i,1,'app_images')"><ArrowDown :size="13"/></button><a class="button small" :href="assetUrl(img.image_url)" target="_blank"><ExternalLink :size="12"/></a><button class="button small" @click="saveImage(img)">保存</button><button class="button small danger" @click="removeImage(img)"><Trash2 :size="12"/>删除</button></div></article></div></template></div>

<div class="sticky-save" style="position:sticky;bottom:0;margin-top:12px"><span>{{editing.id?'修改会写入当前应用':'先创建应用后可继续管理下载与截图'}}</span><div class="page-actions"><button v-if="editing.id" class="button danger" @click="removeApp"><Trash2 :size="13"/>删除应用</button><button class="button primary" :disabled="saving" @click="saveApp(false)">{{saving?'保存中…':'保存应用'}}</button></div></div>
</div></aside></div>
</div></template>
