<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { FileUp, Plus, RefreshCw, Trash2, Save, Download } from '@lucide/vue'
import { del, get, post, put } from '../api'
import { useAppStore } from '../stores/app'
const store=useAppStore();const apps=ref<any[]>([]);const appId=ref<number>(0);const platforms=ref<any[]>([]);const loading=ref(false);const upload=reactive<any>({platform_id:0,version:'1.0.0',changelog:'',file:null});const newPlatform=ref('')
const selectedApp=computed(()=>apps.value.find(a=>Number(a.id)===Number(appId.value)))
async function loadApps(){try{apps.value=await get('/admin/api/apps.php');if(!appId.value&&apps.value.length)appId.value=Number(apps.value[0].id);await loadPlatforms()}catch(e:any){store.notify(e?.message||'应用加载失败','error')}}
async function loadPlatforms(){if(!appId.value){platforms.value=[];return}loading.value=true;try{platforms.value=await get(`/admin/api/attachments.php?app_id=${appId.value}`);if(!upload.platform_id&&platforms.value.length)upload.platform_id=Number(platforms.value[0].id)}catch(e:any){store.notify(e?.message||'附件加载失败','error')}finally{loading.value=false}}
async function addPlatform(){if(!newPlatform.value.trim())return;try{await post('/admin/api/attachments.php',{app_id:appId.value,name:newPlatform.value});newPlatform.value='';await loadPlatforms();store.notify('平台分类已添加')}catch(e:any){store.notify(e?.message||'添加失败','error')}}
async function savePlatform(p:any){try{await put('/admin/api/attachments.php',{id:p.id,name:p.name});store.notify('平台名称已保存')}catch(e:any){store.notify(e?.message||'保存失败','error')}}
async function removePlatform(p:any){if(!confirm(`删除「${p.name}」及其中所有附件文件？`))return;try{await del('/admin/api/attachments.php',{id:p.id});await loadPlatforms();store.notify('平台分类已删除')}catch(e:any){store.notify(e?.message||'删除失败','error')}}
async function uploadFile(){if(!upload.file||!upload.platform_id||!upload.version.trim())return store.notify('请选择文件、平台并填写版本','error');const fd=new FormData();fd.append('app_id',String(appId.value));fd.append('platform_id',String(upload.platform_id));fd.append('version',upload.version);fd.append('changelog',upload.changelog);fd.append('file',upload.file);try{await post('/admin/api/attachment-files.php',fd);upload.file=null;upload.changelog='';await loadPlatforms();store.notify('附件上传完成')}catch(e:any){store.notify(e?.message||'上传失败','error')}}
async function saveFile(f:any){try{await put('/admin/api/attachment-files.php',{id:f.id,version:f.version,changelog:f.changelog});await loadPlatforms();store.notify('附件信息已保存')}catch(e:any){store.notify(e?.message||'保存失败','error')}}
async function removeFile(f:any){if(!confirm(`删除版本 ${f.version} 的文件？`))return;try{await del('/admin/api/attachment-files.php',{id:f.id});await loadPlatforms();store.notify('附件已删除')}catch(e:any){store.notify(e?.message||'删除失败','error')}}
onMounted(loadApps)
</script>
<template><div>
<div class="page-head"><div><h1>附件管理</h1><p>按应用和平台维护可下载附件、版本号与更新说明。</p></div><button class="button" @click="loadPlatforms"><RefreshCw :size="14"/>刷新</button></div>
<div class="toolbar"><select v-model="appId" class="select auto" @change="upload.platform_id=0;loadPlatforms()"><option v-for="a in apps" :key="a.id" :value="Number(a.id)">{{a.name}}</option></select><span class="subtle">{{selectedApp?.slug}}</span></div>
<div v-if="!apps.length" class="empty-state"><b>还没有应用</b>请先在应用管理中创建应用。</div>
<template v-else>
<div class="two-col" style="grid-template-columns:minmax(0,1fr) 330px">
 <section class="panel"><div class="panel-head"><div><h3>{{selectedApp?.name}} 的附件</h3><span>{{platforms.length}} 个平台分类</span></div></div><div v-if="loading" style="padding:14px"><div v-for="i in 4" :key="i" class="skeleton" style="height:46px;margin:8px 0"></div></div><div v-else class="task-list" style="padding:12px"><div v-for="p in platforms" :key="p.id" class="task-card"><div class="task-head"><input v-model="p.name" class="input" style="max-width:220px"><div class="page-actions"><button class="button small" @click="savePlatform(p)"><Save :size="12"/>保存</button><button class="button small danger" @click="removePlatform(p)"><Trash2 :size="12"/></button></div></div><div v-if="p.files?.length" class="table-wrap" style="margin-top:10px"><table class="data-table"><thead><tr><th>版本</th><th>大小</th><th>更新说明</th><th>操作</th></tr></thead><tbody><tr v-for="f in p.files" :key="f.id"><td><input v-model="f.version" class="input" style="width:100px"></td><td>{{f.file_size}}</td><td><input v-model="f.changelog" class="input" style="min-width:200px"></td><td><div class="page-actions"><a class="button small" :href="f.file_url" target="_blank"><Download :size="12"/></a><button class="button small" @click="saveFile(f)">保存</button><button class="button small danger" @click="removeFile(f)">删除</button></div></td></tr></tbody></table></div><p v-else class="subtle">该平台暂无附件。</p></div><div v-if="!platforms.length" class="empty-state">暂无平台分类，请先在右侧添加。</div></div></section>
 <aside><section class="form-card"><div class="form-section"><h3>新增平台分类</h3><p>例如 Windows、macOS、Android TV。</p><div class="toolbar"><input v-model="newPlatform" class="input" placeholder="平台名称"><button class="button primary" @click="addPlatform"><Plus :size="13"/></button></div></div></section><section class="form-card" style="margin-top:12px"><div class="form-section"><h3>上传附件</h3><p>文件会进入当前租户/站点自己的 uploads 区域。</p><div class="field"><label>平台</label><select v-model="upload.platform_id" class="select"><option :value="0">请选择</option><option v-for="p in platforms" :key="p.id" :value="Number(p.id)">{{p.name}}</option></select></div><div class="field" style="margin-top:9px"><label>版本</label><input v-model="upload.version" class="input"></div><div class="field" style="margin-top:9px"><label>更新说明</label><textarea v-model="upload.changelog" class="textarea"></textarea></div><label class="drop-zone" style="display:block;margin-top:10px"><FileUp :size="22" style="margin:auto"/><b>{{upload.file?.name||'选择附件文件'}}</b><span>点击选择，提交后显示真实上传结果。</span><input type="file" hidden @change="upload.file=($event.target as HTMLInputElement).files?.[0]||null"></label><button class="button primary" style="width:100%;margin-top:10px" @click="uploadFile">上传附件</button></div></section></aside>
</div>
</template>
</div></template>
