<script setup lang="ts">
import { computed, ref } from 'vue'
import { Download, Upload, ShieldCheck } from '@lucide/vue'
import { downloadPost, post } from '../api'
import { useAppStore } from '../stores/app'
const store=useAppStore();const password=ref('');const passwordConfirm=ref('');const includeUploads=ref(true);const exporting=ref(false);const importFile=ref<File|null>(null);const importPassword=ref('');const preview=ref<any>(null);const importing=ref(false)
const tableGroups=[
 {name:'核心配置',tables:['site_settings','apps','app_downloads','app_images','feature_categories','feature_cards','friend_links','custom_code']},
 {name:'附件与资源',tables:['app_platforms','app_attachments','image_categories','image_library']},
 {name:'构建与签名',tables:['generated_mobileconfigs','generated_apks','generated_ipas','keystores','mc_certificates']},
 {name:'账户',tables:['admin_users']},
]
const selected=ref<string[]>(tableGroups.flatMap(g=>g.tables));const previewTables=computed(()=>Object.keys(preview.value?.tables||{}));const importSelected=ref<string[]>([]);const importUploads=ref(true)
function toggle(table:string){selected.value=selected.value.includes(table)?selected.value.filter(x=>x!==table):[...selected.value,table]}
async function exportBackup(){
  if(!selected.value.length&&!includeUploads.value)return store.notify('请选择至少一项导出内容','error')
  if(password.value&&password.value.length<8)return store.notify('加密密码至少 8 位','error')
  if(password.value!==passwordConfirm.value)return store.notify('两次输入的加密密码不一致','error')
  exporting.value=true
  try{const {blob,filename}=await downloadPost('/admin/api/backup.php',{action:'export',password:password.value,tables:selected.value,include_uploads:includeUploads.value});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);store.notify(password.value?'完整加密备份已生成':'普通 ZIP 已生成；签名私钥和密码未包含')}
  catch(e:any){store.notify(e?.message||'导出失败','error')}finally{exporting.value=false}
}
async function inspect(){if(!importFile.value)return store.notify('请选择备份文件','error');const fd=new FormData();fd.append('action','decrypt_preview');fd.append('password',importPassword.value);fd.append('file',importFile.value);try{preview.value=await post('/admin/api/backup.php',fd);importSelected.value=Object.keys(preview.value.tables||{}).filter(t=>t!=='admin_users');importUploads.value=!!preview.value.has_uploads;store.notify('备份已解析')}catch(e:any){store.notify(e?.message||'备份解析失败','error')}}
async function restore(){if(!importFile.value||!preview.value)return;if(!importSelected.value.length&&!importUploads.value)return store.notify('请选择至少一项恢复内容','error');if(!confirm('导入会覆盖所选数据表与文件，此操作不可逆。确定继续？'))return;const fd=new FormData();fd.append('action','import');fd.append('password',importPassword.value);fd.append('tables',JSON.stringify(importSelected.value));fd.append('include_uploads',importUploads.value?'1':'0');fd.append('file',importFile.value);importing.value=true;try{const res:any=await post('/admin/api/backup.php',fd);store.notify(res.message||'备份已恢复')}catch(e:any){store.notify(e?.message||'导入失败','error')}finally{importing.value=false}}
</script>
<template><div>
<div class="page-head"><div><h1>导入导出</h1><p>支持 v3 与旧版 AppDown 备份；完整备份使用 AES-256-GCM + Argon2id / PBKDF2。</p></div></div>
<div class="two-col">
 <section class="form-card"><div class="panel-head"><div><h3><Download :size="13" style="display:inline;vertical-align:-2px;margin-right:5px"/>导出备份</h3><span>选择需要导出的数据与上传文件。</span></div></div><div class="form-section"><div v-for="g in tableGroups" :key="g.name" style="margin-bottom:14px"><b style="font-size:10.5px">{{g.name}}</b><div class="check-list" style="margin-top:7px"><label v-for="t in g.tables" :key="t" class="check-row"><input type="checkbox" :checked="selected.includes(t)" @change="toggle(t)">{{t}}</label></div></div><label class="check-row"><input v-model="includeUploads" type="checkbox">包含 uploads 文件</label><div class="form-grid" style="margin-top:14px"><div class="field"><label>加密密码（可选）</label><input v-model="password" type="password" class="input" minlength="8" autocomplete="new-password" placeholder="至少 8 位；完整迁移签名材料时建议填写"><small>留空生成普通 ZIP，并主动排除私钥与 Keystore 密码。</small></div><div class="field"><label>确认加密密码</label><input v-model="passwordConfirm" type="password" class="input" autocomplete="new-password" placeholder="再次输入；留空密码时同样留空"></div></div><button class="button primary" style="margin-top:14px" :disabled="exporting" @click="exportBackup"><ShieldCheck :size="14"/>{{exporting?'正在生成…':'生成备份'}}</button></div></section>
 <section class="form-card"><div class="panel-head"><div><h3><Upload :size="13" style="display:inline;vertical-align:-2px;margin-right:5px"/>恢复备份</h3><span>先解析预览，再选择要覆盖的内容。</span></div></div><div class="form-section"><label class="drop-zone" style="display:block"><Upload :size="22" style="margin:auto"/><b>{{importFile?.name||'选择 .zip / .enc 备份'}}</b><span>支持 v3、旧版 ZIP、纯 JSON 与旧 AES-GCM 备份。</span><input type="file" hidden accept=".zip,.enc" @change="importFile=($event.target as HTMLInputElement).files?.[0]||null;preview=null"></label><div class="field" style="margin-top:10px"><label>备份密码</label><input v-model="importPassword" type="password" class="input"></div><button class="button" style="margin-top:10px" @click="inspect">解析备份</button><div v-if="preview" style="margin-top:14px"><div class="task-card"><div class="task-head"><b>备份 {{preview.meta?.version||'未知版本'}}</b><span class="badge">可读取</span></div><p>{{preview.meta?.exported_at}} · {{preview.uploads_count||0}} 个文件 · {{preview.uploads_size||'0 KB'}}</p><p class="subtle">{{preview.meta?.signing_materials_included?'包含签名材料':'不包含签名私钥'}}</p></div><div class="check-list" style="margin-top:10px"><label v-for="t in previewTables" :key="t" class="check-row"><input v-model="importSelected" type="checkbox" :value="t">{{t}} <span class="subtle">({{preview.tables[t]}})</span><span v-if="t==='admin_users'" class="badge warning">账户</span></label><label v-if="preview.has_uploads" class="check-row"><input v-model="importUploads" type="checkbox">恢复 uploads 文件</label></div><button class="button primary" style="margin-top:12px" :disabled="importing" @click="restore">{{importing?'正在恢复…':'确认恢复所选数据'}}</button></div></div></section>
</div>
<div class="card" style="margin-top:13px"><h3>备份安全说明</h3><div class="status-grid" style="margin-top:10px"><div class="status-card"><b>完整加密备份</b><p>AES-256-GCM；优先 Argon2id，无 sodium 时回退 PBKDF2-HMAC-SHA256。</p></div><div class="status-card"><b>无密码 ZIP</b><p>不包含私钥、Keystore 密码和敏感签名文件。</p></div><div class="status-card"><b>导入检查</b><p>服务端检查路径遍历、文件数量、解压总量与异常压缩比。</p></div></div></div>
</div></template>
