<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, reactive, ref } from 'vue'
import { Hammer, RefreshCw, Square, Smartphone, Apple } from '@lucide/vue'
import { get, post } from '../api'
import { useAppStore } from '../stores/app'
const store=useAppStore();const mode=ref<'apk'|'ipa'>('apk');const keystores=ref<any[]>([]);const tasks=ref<any[]>([]);const active=ref<any>(null);let timer:number|undefined
const apk=reactive({action:'build',url:'https://',app_name:'AppDown Client',package_name:'org.appdown.client',version_name:'1.0.0',version_code:1,keystore_id:0,icon_url:'',splash_url:'',splash_color:'#FFFFFF',status_bar_color:'#000000'})
const ipa=reactive({action:'build_ipa',url:'https://',app_name:'AppDown Client',bundle_id:'org.appdown.client',version_name:'1.0.0',version_code:1,icon_url:'',status_bar_color:'#000000'})
const progress=computed(()=>Number(active.value?.progress||0));const running=computed(()=>active.value&&['pending','building'].includes(active.value.status))
async function loadMeta(){try{keystores.value=await get('/admin/api/keystores.php');if(!apk.keystore_id&&keystores.value.length)apk.keystore_id=Number(keystores.value[0].id);await loadTasks()}catch(e:any){store.notify(e?.message||'构建环境数据加载失败','error')}}
async function loadTasks(){try{tasks.value=await get(`/admin/api/generate.php?action=${mode.value==='apk'?'list_tasks':'list_ipa_tasks'}`);const r=tasks.value.find(t=>['pending','building'].includes(t.status));if(r){active.value=r;startPoll(Number(r.id))}}catch(e:any){store.notify(e?.message||'任务列表加载失败','error')}}
async function build(){try{const payload=mode.value==='apk'?apk:ipa;const res:any=await post('/admin/api/generate.php',payload);active.value={id:res.task_id,status:'pending',progress:0,progress_msg:'任务已创建'};store.notify(`${mode.value.toUpperCase()} 构建任务已创建`);startPoll(Number(res.task_id));await loadTasks()}catch(e:any){store.notify(e?.message||'创建构建任务失败','error')}}
function startPoll(id:number){if(timer)clearInterval(timer);const poll=async()=>{try{active.value=await get(`/admin/api/generate.php?action=task_status&id=${id}`);if(!['pending','building'].includes(active.value.status)){if(timer)clearInterval(timer);timer=undefined;store.notify(active.value.status==='success'?'构建完成':'构建已结束',active.value.status==='success'?'success':'error');await loadTasks()}}catch{}};poll();timer=window.setInterval(poll,1500)}
async function cancel(){if(!active.value?.id||!confirm('确定取消当前构建任务？'))return;try{await post('/admin/api/generate.php',{action:'cancel_task',task_id:active.value.id});store.notify('已请求取消任务','info');await loadTasks()}catch(e:any){store.notify(e?.message||'取消失败','error')}}
function switchMode(v:'apk'|'ipa'){mode.value=v;active.value=null;if(timer)clearInterval(timer);loadTasks()}
onMounted(loadMeta);onBeforeUnmount(()=>{if(timer)clearInterval(timer)})
</script>
<template><div>
<div class="page-head"><div><h1>生成应用</h1><p>使用现有 PHP Worker 构建 APK / IPA，Vue 前端实时轮询任务进度，无需刷新页面。</p></div><button class="button" @click="loadMeta"><RefreshCw :size="14"/>刷新</button></div>
<div class="drawer-tabs" style="width:max-content;margin-bottom:13px"><button :class="{active:mode==='apk'}" @click="switchMode('apk')"><Smartphone :size="13" style="display:inline;vertical-align:-2px"/> Android APK</button><button :class="{active:mode==='ipa'}" @click="switchMode('ipa')"><Apple :size="13" style="display:inline;vertical-align:-2px"/> iOS IPA</button></div>
<div class="builder-layout">
 <section class="builder-box"><div class="panel-head"><div><h3>新建 {{mode.toUpperCase()}} 构建</h3><span>提交后由后台 Worker 执行</span></div></div><div class="form-section" v-if="mode==='apk'"><div class="field"><label>目标 URL</label><input v-model="apk.url" class="input"></div><div class="field" style="margin-top:9px"><label>应用名称</label><input v-model="apk.app_name" class="input"></div><div class="field" style="margin-top:9px"><label>Package Name</label><input v-model="apk.package_name" class="input"></div><div class="form-grid" style="margin-top:9px"><div class="field"><label>版本名</label><input v-model="apk.version_name" class="input"></div><div class="field"><label>Version Code</label><input v-model.number="apk.version_code" type="number" min="1" class="input"></div></div><div class="field" style="margin-top:9px"><label>签名 Keystore</label><select v-model.number="apk.keystore_id" class="select"><option :value="0">请选择</option><option v-for="k in keystores" :key="k.id" :value="Number(k.id)">{{k.name}} · {{k.alias}}</option></select><small v-if="!keystores.length">没有可用 Keystore，请先在旧密钥管理能力中创建/导入；密钥 API 已保持不变。</small></div><div class="field" style="margin-top:9px"><label>图标 URL</label><input v-model="apk.icon_url" class="input"></div><div class="field" style="margin-top:9px"><label>启动图 URL</label><input v-model="apk.splash_url" class="input"></div><div class="form-grid" style="margin-top:9px"><div class="field"><label>启动背景</label><input v-model="apk.splash_color" type="color" class="input" style="padding:4px"></div><div class="field"><label>状态栏</label><input v-model="apk.status_bar_color" type="color" class="input" style="padding:4px"></div></div></div><div class="form-section" v-else><div class="field"><label>目标 URL</label><input v-model="ipa.url" class="input"></div><div class="field" style="margin-top:9px"><label>应用名称</label><input v-model="ipa.app_name" class="input"></div><div class="field" style="margin-top:9px"><label>Bundle ID</label><input v-model="ipa.bundle_id" class="input"></div><div class="form-grid" style="margin-top:9px"><div class="field"><label>版本</label><input v-model="ipa.version_name" class="input"></div><div class="field"><label>Build Number</label><input v-model.number="ipa.version_code" type="number" min="1" class="input"></div></div><div class="field" style="margin-top:9px"><label>图标 URL</label><input v-model="ipa.icon_url" class="input"></div><div class="field" style="margin-top:9px"><label>状态栏颜色</label><input v-model="ipa.status_bar_color" type="color" class="input" style="padding:4px"></div></div><div style="padding:0 17px 17px"><button class="button primary" style="width:100%" :disabled="!!running" @click="build"><Hammer :size="14"/>{{running?'当前有任务正在构建':'开始构建'}}</button></div></section>
 <section class="builder-box"><div class="panel-head"><div><h3>当前任务</h3><span>每 1.5 秒自动同步后端真实状态</span></div><button v-if="running" class="button small danger" @click="cancel"><Square :size="12"/>取消</button></div><div v-if="active" class="builder-progress"><div class="task-head"><b>#{{active.id}} · {{active.status}}</b><span class="subtle">{{progress}}%</span></div><div class="progress"><div :style="{width:progress+'%'}"></div></div><div class="steps"><div class="step" :class="{done:progress>=5,active:progress<20}"><span class="step-dot">{{progress>=20?'✓':'1'}}</span>准备项目</div><div class="step" :class="{done:progress>=35,active:progress>=20&&progress<55}"><span class="step-dot">{{progress>=55?'✓':'2'}}</span>生成资源</div><div class="step" :class="{done:progress>=70,active:progress>=55&&progress<80}"><span class="step-dot">{{progress>=80?'✓':'3'}}</span>编译</div><div class="step" :class="{done:progress>=90,active:progress>=80&&progress<95}"><span class="step-dot">{{progress>=95?'✓':'4'}}</span>签名</div><div class="step" :class="{done:progress>=100,active:progress>=95&&progress<100}"><span class="step-dot">{{progress>=100?'✓':'5'}}</span>完整性验证</div></div><div class="log-box">状态：{{active.progress_msg || active.status}}\n<span v-if="active.error_msg">错误：{{active.error_msg}}</span><span v-if="active.result_url">\n结果：{{active.result_url}}\n大小：{{active.result_size}}</span></div><a v-if="active.result_url" class="button primary" :href="active.result_url" target="_blank" style="margin-top:10px">下载构建结果</a></div><div v-else class="empty-state" style="margin:14px"><b>当前没有构建任务</b>提交任务后这里会实时显示进度。</div></section>
</div>
<section class="panel" style="margin-top:13px"><div class="panel-head"><div><h3>最近任务</h3><span>{{mode.toUpperCase()}} 构建历史</span></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>ID</th><th>应用</th><th>标识</th><th>状态</th><th>进度</th><th>更新时间</th><th>结果</th></tr></thead><tbody><tr v-for="t in tasks" :key="t.id"><td>#{{t.id}}</td><td>{{t.app_name||'—'}}</td><td>{{t.package_name||t.bundle_id||'—'}}</td><td><span class="badge" :class="{warning:['pending','building'].includes(t.status),danger:t.status==='failed',muted:t.status==='cancelled'}">{{t.status}}</span></td><td>{{t.progress}}%</td><td>{{t.updated_at}}</td><td><a v-if="t.result_url" :href="t.result_url" target="_blank" class="link-button">下载</a><span v-else>—</span></td></tr><tr v-if="!tasks.length"><td colspan="7" class="subtle">暂无任务</td></tr></tbody></table></div></section>
</div></template>
