<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Plus, RefreshCw, Save, Trash2 } from 'lucide-vue-next'
import { del, get, post, put } from '../api'
import { useAppStore } from '../stores/app'
const store=useAppStore();const tab=ref<'features'|'links'>('features');const loading=ref(false);const features=ref<any[]>([]);const categories=ref<any[]>([]);const links=ref<any[]>([])
const featureDraft=reactive<any>({title:'',description:'',icon:'fas fa-star',icon_url:'',category_id:0});const categoryName=ref('');const linkDraft=reactive<any>({name:'',url:'https://',icon:'fas fa-link',icon_url:'',show_icon:1})
async function load(){loading.value=true;try{[features.value,categories.value,links.value]=await Promise.all([get('/admin/api/features.php'),get('/admin/api/features.php?action=categories'),get('/admin/api/links.php')])}catch(e:any){store.notify(e?.message||'内容组件加载失败','error')}finally{loading.value=false}}
async function addCategory(){if(!categoryName.value.trim())return;try{await post('/admin/api/features.php?action=categories',{name:categoryName.value});categoryName.value='';await load();store.notify('分类已添加')}catch(e:any){store.notify(e?.message||'添加失败','error')}}
async function removeCategory(c:any){if(!confirm(`删除分类「${c.name}」？卡片会变为未分类。`))return;try{await del('/admin/api/features.php?action=categories',{id:c.id});await load();store.notify('分类已删除')}catch(e:any){store.notify(e?.message||'删除失败','error')}}
async function addFeature(){if(!featureDraft.title.trim())return store.notify('标题不能为空','error');try{await post('/admin/api/features.php',featureDraft);Object.assign(featureDraft,{title:'',description:'',icon:'fas fa-star',icon_url:'',category_id:0});await load();store.notify('特色卡片已添加')}catch(e:any){store.notify(e?.message||'添加失败','error')}}
async function saveFeature(f:any){try{await put('/admin/api/features.php',f);store.notify('卡片已保存')}catch(e:any){store.notify(e?.message||'保存失败','error')}}
async function removeFeature(f:any){if(!confirm(`删除「${f.title}」？`))return;try{await del('/admin/api/features.php',{id:f.id});features.value=features.value.filter(x=>x.id!==f.id);store.notify('卡片已删除')}catch(e:any){store.notify(e?.message||'删除失败','error')}}
async function addLink(){if(!linkDraft.name.trim())return store.notify('链接名称不能为空','error');try{await post('/admin/api/links.php',linkDraft);Object.assign(linkDraft,{name:'',url:'https://',icon:'fas fa-link',icon_url:'',show_icon:1});await load();store.notify('友情链接已添加')}catch(e:any){store.notify(e?.message||'添加失败','error')}}
async function saveLink(l:any){try{await put('/admin/api/links.php',l);store.notify('链接已保存')}catch(e:any){store.notify(e?.message||'保存失败','error')}}
async function removeLink(l:any){if(!confirm(`删除「${l.name}」？`))return;try{await del('/admin/api/links.php',{id:l.id});links.value=links.value.filter(x=>x.id!==l.id);store.notify('链接已删除')}catch(e:any){store.notify(e?.message||'删除失败','error')}}
onMounted(load)
</script>
<template><div>
<div class="page-head"><div><h1>内容组件</h1><p>统一管理分发页特色卡片、分类与友情链接；模板 2.0 会按各自布局重新组合这些组件。</p></div><button class="button" @click="load"><RefreshCw :size="14"/>刷新</button></div>
<div class="drawer-tabs" style="width:max-content;margin-bottom:13px"><button :class="{active:tab==='features'}" @click="tab='features'">特色卡片</button><button :class="{active:tab==='links'}" @click="tab='links'">友情链接</button></div>
<template v-if="tab==='features'">
 <div class="two-col" style="grid-template-columns:minmax(0,1fr) 290px">
  <div><section class="form-card"><div class="form-section"><h3>新增特色卡片</h3><p>卡片可绑定分类，应用可选择分类来展示一组独立特色。</p><div class="form-grid"><div class="field"><label>标题</label><input v-model="featureDraft.title" class="input"></div><div class="field"><label>分类</label><select v-model="featureDraft.category_id" class="select"><option :value="0">未分类 / 全局</option><option v-for="c in categories" :value="Number(c.id)" :key="c.id">{{c.name}}</option></select></div><div class="field"><label>图标类</label><input v-model="featureDraft.icon" class="input"></div><div class="field"><label>图片图标 URL</label><input v-model="featureDraft.icon_url" class="input"></div><div class="field full"><label>说明</label><textarea v-model="featureDraft.description" class="textarea"></textarea></div></div><button class="button primary" style="margin-top:10px" @click="addFeature"><Plus :size="13"/>添加卡片</button></div></section>
  <div class="three-col" style="margin-top:12px"><article v-for="f in features" :key="f.id" class="card"><div class="field"><label>标题</label><input v-model="f.title" class="input"></div><div class="field" style="margin-top:8px"><label>说明</label><textarea v-model="f.description" class="textarea"></textarea></div><div class="form-grid" style="margin-top:8px"><div class="field"><label>分类</label><select v-model="f.category_id" class="select"><option :value="0">未分类</option><option v-for="c in categories" :value="Number(c.id)" :key="c.id">{{c.name}}</option></select></div><div class="field"><label>状态</label><select v-model="f.is_active" class="select"><option :value="1">启用</option><option :value="0">停用</option></select></div></div><div class="page-actions" style="margin-top:10px"><button class="button small" @click="saveFeature(f)"><Save :size="12"/>保存</button><button class="button small danger" @click="removeFeature(f)"><Trash2 :size="12"/>删除</button></div></article></div></div>
  <aside class="card"><h3>分类</h3><p class="subtle">给不同应用绑定不同特色卡片组。</p><div class="toolbar" style="margin-top:12px"><input v-model="categoryName" class="input" placeholder="新分类名称"><button class="button primary" @click="addCategory"><Plus :size="13"/></button></div><div class="task-list"><div v-for="c in categories" :key="c.id" class="task-card"><div class="task-head"><b>{{c.name}}</b><span class="badge muted">{{c.card_count||0}} 卡片</span></div><button class="link-button" style="margin-top:7px;color:var(--danger)" @click="removeCategory(c)">删除分类</button></div></div></aside>
 </div>
</template>
<template v-else>
 <section class="form-card"><div class="form-section"><h3>新增友情链接</h3><p>友情链接会继续使用公开页现有安全链接处理。</p><div class="form-grid"><div class="field"><label>名称</label><input v-model="linkDraft.name" class="input"></div><div class="field"><label>URL</label><input v-model="linkDraft.url" class="input"></div><div class="field"><label>图标类</label><input v-model="linkDraft.icon" class="input"></div><div class="field"><label>图标 URL</label><input v-model="linkDraft.icon_url" class="input"></div></div><button class="button primary" style="margin-top:10px" @click="addLink"><Plus :size="13"/>添加链接</button></div></section>
 <div class="panel" style="margin-top:12px"><div class="table-wrap"><table class="data-table"><thead><tr><th>名称</th><th>URL</th><th>图标</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="l in links" :key="l.id"><td><input v-model="l.name" class="input" style="min-width:130px"></td><td><input v-model="l.url" class="input" style="min-width:240px"></td><td><input v-model="l.icon" class="input" style="min-width:140px"></td><td><select v-model="l.is_active" class="select"><option :value="1">启用</option><option :value="0">停用</option></select></td><td><div class="page-actions"><button class="button small" @click="saveLink(l)">保存</button><button class="button small danger" @click="removeLink(l)">删除</button></div></td></tr></tbody></table></div></div>
</template>
</div></template>
