<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { FileKey2, Plus, RefreshCw, Trash2, ExternalLink, Save } from 'lucide-vue-next'
import { del, get, post, put } from '../api'
import { useAppStore } from '../stores/app'
const store=useAppStore();const tab=ref<'profiles'|'certs'>('profiles');const profiles=ref<any[]>([]);const certs=ref<any[]>([]);const apps=ref<any[]>([]);const generating=ref(false)
const form=reactive<any>({display_name:'AppDown',target_url:'https://',bundle_id:'com.appdown.webclip',version:'1',fullscreen:true,icon_data:'',description:'',payload_org:'',cert_id:0,template:'modern'})
const certDraft=reactive<any>({name:'签名证书',mode:'text',cert:'',key:'',chain:'',payload_org:'',is_global:1})
async function load(){try{[profiles.value,certs.value,apps.value]=await Promise.all([get('/admin/api/mobileconfig.php?action=list'),get('/admin/api/mobileconfig.php?action=list_certs'),get('/admin/api/apps.php')]);if(!form.cert_id){const g=certs.value.find(c=>Number(c.is_global));if(g)form.cert_id=Number(g.id)}}catch(e:any){store.notify(e?.message||'Mobileconfig 数据加载失败','error')}}
async function generate(){generating.value=true;try{const r:any=await post('/admin/api/mobileconfig.php',{action:'generate',...form});store.notify(r.signed?'Mobileconfig 已生成并签名':'Mobileconfig 已生成（未签名）');await load()}catch(e:any){store.notify(e?.message||'生成失败','error')}finally{generating.value=false}}
async function removeProfile(p:any){if(!confirm(`删除「${p.display_name}」及文件？`))return;try{await del('/admin/api/mobileconfig.php',{id:p.id});profiles.value=profiles.value.filter(x=>x.id!==p.id);store.notify('Mobileconfig 已删除')}catch(e:any){store.notify(e?.message||'删除失败','error')}}
async function createCert(){try{await post('/admin/api/mobileconfig.php',{action:'create_cert',...certDraft});Object.assign(certDraft,{name:'签名证书',mode:'text',cert:'',key:'',chain:'',payload_org:'',is_global:0});await load();store.notify('证书已保存')}catch(e:any){store.notify(e?.message||'证书保存失败','error')}}
async function setGlobal(c:any){try{await put('/admin/api/mobileconfig.php',{action:'update_cert',id:c.id,name:c.name,mode:c.mode,payload_org:c.payload_org||'',is_global:1,cert:'',key:'',chain:''});await load();store.notify('已设为全局默认证书')}catch(e:any){store.notify(e?.message||'设置失败','error')}}
async function removeCert(c:any){if(!confirm(`删除证书「${c.name}」？被 Mobileconfig 引用时后端会拒绝。`))return;try{await del('/admin/api/mobileconfig.php',{action:'delete_cert',id:c.id});await load();store.notify('证书已删除')}catch(e:any){store.notify(e?.message||'删除失败','error')}}
onMounted(load)
</script>
<template><div>
<div class="page-head"><div><h1>Mobileconfig</h1><p>生成 iOS WebClip 配置文件并管理签名证书；私钥永远不会通过 GET 回传到浏览器。</p></div><button class="button" @click="load"><RefreshCw :size="14"/>刷新</button></div>
<div class="drawer-tabs" style="width:max-content;margin-bottom:13px"><button :class="{active:tab==='profiles'}" @click="tab='profiles'">配置文件</button><button :class="{active:tab==='certs'}" @click="tab='certs'">签名证书</button></div>
<template v-if="tab==='profiles'">
 <div class="two-col" style="grid-template-columns:330px minmax(0,1fr)"><section class="form-card"><div class="form-section"><h3><FileKey2 :size="13" style="display:inline;vertical-align:-2px;margin-right:5px"/>生成配置文件</h3><p>生成逻辑仍由现有 PHP mobileconfig 模块完成。</p><div class="field"><label>显示名称</label><input v-model="form.display_name" class="input"></div><div class="field" style="margin-top:9px"><label>目标 URL</label><input v-model="form.target_url" class="input"></div><div class="field" style="margin-top:9px"><label>Bundle ID</label><input v-model="form.bundle_id" class="input"></div><div class="form-grid" style="margin-top:9px"><div class="field"><label>版本</label><input v-model="form.version" class="input"></div><div class="field"><label>模板</label><select v-model="form.template" class="select"><option value="modern">modern</option><option value="classic">classic</option><option value="minimal">minimal</option></select></div></div><div class="field" style="margin-top:9px"><label>签名证书</label><select v-model.number="form.cert_id" class="select"><option :value="0">使用全局证书 / 不签名</option><option v-for="c in certs" :key="c.id" :value="Number(c.id)">{{c.name}}</option></select></div><div class="field" style="margin-top:9px"><label>Payload Organization</label><input v-model="form.payload_org" class="input"></div><div class="field" style="margin-top:9px"><label>说明</label><textarea v-model="form.description" class="textarea"></textarea></div><label class="check-row" style="margin-top:9px"><input v-model="form.fullscreen" type="checkbox">全屏 WebClip</label><button class="button primary" style="width:100%;margin-top:12px" :disabled="generating" @click="generate"><Plus :size="13"/>{{generating?'正在生成…':'生成 Mobileconfig'}}</button></div></section>
 <section class="panel"><div class="panel-head"><div><h3>已生成配置文件</h3><span>{{profiles.length}} 个</span></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>名称</th><th>目标</th><th>版本</th><th>签名</th><th>文件</th><th>操作</th></tr></thead><tbody><tr v-for="p in profiles" :key="p.id"><td>{{p.display_name}}</td><td style="max-width:260px;overflow:hidden;text-overflow:ellipsis">{{p.target_url}}</td><td>{{p.version}}</td><td><span class="badge" :class="{muted:!p.cert_id}">{{p.cert_name||'未签名'}}</span></td><td>{{p.file_size}}</td><td><div class="page-actions"><a v-if="p.file_path" :href="'/' + String(p.file_path).replace(/^\//,'')" target="_blank" class="button small"><ExternalLink :size="12"/>打开</a><button class="button small danger" @click="removeProfile(p)"><Trash2 :size="12"/>删除</button></div></td></tr><tr v-if="!profiles.length"><td colspan="6" class="subtle">暂无配置文件</td></tr></tbody></table></div></section></div>
</template>
<template v-else>
 <div class="two-col" style="grid-template-columns:380px minmax(0,1fr)"><section class="form-card"><div class="form-section"><h3>新增签名证书</h3><p>支持 PEM 文本或服务器路径模式。私钥保存后加密，之后页面只显示“已配置”。</p><div class="field"><label>名称</label><input v-model="certDraft.name" class="input"></div><div class="field" style="margin-top:9px"><label>模式</label><select v-model="certDraft.mode" class="select"><option value="text">PEM 文本</option><option value="path">服务器路径</option></select></div><div class="field" style="margin-top:9px"><label>证书 / 证书路径</label><textarea v-model="certDraft.cert" class="textarea" style="min-height:120px"></textarea></div><div class="field" style="margin-top:9px"><label>私钥 / 私钥路径</label><textarea v-model="certDraft.key" class="textarea" style="min-height:120px"></textarea></div><div class="field" style="margin-top:9px"><label>证书链（可选）</label><textarea v-model="certDraft.chain" class="textarea"></textarea></div><div class="field" style="margin-top:9px"><label>Payload Organization</label><input v-model="certDraft.payload_org" class="input"></div><label class="check-row" style="margin-top:9px"><input v-model="certDraft.is_global" type="checkbox" :true-value="1" :false-value="0">设为全局默认</label><button class="button primary" style="margin-top:12px" @click="createCert"><Save :size="13"/>保存证书</button></div></section>
 <section class="panel"><div class="panel-head"><div><h3>证书列表</h3><span>{{certs.length}} 个</span></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>名称</th><th>模式</th><th>状态</th><th>颁发者</th><th>有效期</th><th>操作</th></tr></thead><tbody><tr v-for="c in certs" :key="c.id"><td>{{c.name}}</td><td>{{c.mode}}</td><td><span class="badge" :class="{warning:!c.has_key}">{{c.is_global?'全局 · ':''}}{{c.has_key?'私钥已配置':'缺少私钥'}}</span></td><td>{{c.cert_issuer||'—'}}</td><td>{{c.cert_expires||'—'}}</td><td><div class="page-actions"><button v-if="!Number(c.is_global)" class="button small" @click="setGlobal(c)">设为默认</button><button class="button small danger" @click="removeCert(c)"><Trash2 :size="12"/>删除</button></div></td></tr><tr v-if="!certs.length"><td colspan="6" class="subtle">暂无证书</td></tr></tbody></table></div></section></div>
</template>
</div></template>
