<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ExternalLink, FileKey2, Link2, Pencil, Plus, RefreshCw, Save, Trash2, Upload, X } from '@lucide/vue'
import { del, get, post, put } from '../api'
import { useAppStore } from '../stores/app'

const store=useAppStore();const tab=ref<'profiles'|'certs'>('profiles');const profiles=ref<any[]>([]);const certs=ref<any[]>([]);const apps=ref<any[]>([]);const generating=ref(false);const profileEditing=ref(0);const certEditing=ref(0)
const form=reactive<any>({display_name:'AppDown',target_url:'https://',bundle_id:'com.appdown.webclip',version:'1',fullscreen:true,icon_data:'',description:'',payload_org:'',cert_id:0,template:'modern'})
const certDraft=reactive<any>({name:'签名证书',mode:'text',cert:'',key:'',chain:'',payload_org:'',is_global:0})
const profilePlatforms=reactive<Record<number,any[]>>({})

function resetProfile(){profileEditing.value=0;Object.assign(form,{display_name:'AppDown',target_url:'https://',bundle_id:'com.appdown.webclip',version:'1',fullscreen:true,icon_data:'',description:'',payload_org:'',cert_id:0,template:'modern'});const g=certs.value.find(c=>Number(c.is_global));if(g)form.cert_id=Number(g.id)}
function resetCert(){certEditing.value=0;Object.assign(certDraft,{name:'签名证书',mode:'text',cert:'',key:'',chain:'',payload_org:'',is_global:0})}
async function load(){try{[profiles.value,certs.value,apps.value]=await Promise.all([get('/admin/api/mobileconfig.php?action=list'),get('/admin/api/mobileconfig.php?action=list_certs'),get('/admin/api/apps.php')]);profiles.value=profiles.value.map(p=>({...p,_appId:Number(p.app_id||0),_platformId:0,_version:p.version||'1.0'}));for(const p of profiles.value)if(p._appId)await loadPlatforms(p);if(!profileEditing.value&&!form.cert_id){const g=certs.value.find(c=>Number(c.is_global));if(g)form.cert_id=Number(g.id)}}catch(e:any){store.notify(e?.message||'Mobileconfig 数据加载失败','error')}}
async function saveProfile(){generating.value=true;try{if(profileEditing.value){await put('/admin/api/mobileconfig.php',{action:'update',id:profileEditing.value,...form});store.notify('Mobileconfig 已重新生成并保存')}else{const r:any=await post('/admin/api/mobileconfig.php',{action:'generate',...form});store.notify(r.signed?'Mobileconfig 已生成并签名':'Mobileconfig 已生成（未签名）')}resetProfile();await load()}catch(e:any){store.notify(e?.message||'保存失败','error')}finally{generating.value=false}}
function editProfile(p:any){profileEditing.value=Number(p.id);Object.assign(form,{display_name:p.display_name||'',target_url:p.target_url||'',bundle_id:p.bundle_id||'',version:p.version||'1',fullscreen:!!Number(p.fullscreen),icon_data:p.icon_data||'',description:p.description||'',payload_org:p.payload_org||'',cert_id:Number(p.cert_id||0),template:p.template||'modern'});window.scrollTo({top:0,behavior:'smooth'})}
async function renameProfile(p:any){const n=prompt('新的文件名（可省略 .mobileconfig）',String(p.file_path||'').split('/').pop()||p.display_name)?.trim();if(!n)return;try{const r:any=await put('/admin/api/mobileconfig.php',{action:'rename',id:p.id,new_name:n});p.file_path=r.new_path||p.file_path;store.notify('文件已重命名')}catch(e:any){store.notify(e?.message||'重命名失败','error')}}
async function removeProfile(p:any){if(!confirm(`删除「${p.display_name}」及文件？`))return;try{await del('/admin/api/mobileconfig.php',{id:p.id});profiles.value=profiles.value.filter(x=>x.id!==p.id);if(profileEditing.value===Number(p.id))resetProfile();store.notify('Mobileconfig 已删除')}catch(e:any){store.notify(e?.message||'删除失败','error')}}
async function iconFile(file?:File){if(!file)return;try{const data=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||''));r.onerror=()=>reject(new Error('读取失败'));r.readAsDataURL(file)});form.icon_data=data.includes(',')?data.split(',')[1]:data;store.notify('WebClip 图标已载入，保存时会写入配置文件')}catch(e:any){store.notify(e?.message||'图标读取失败','error')}}
async function loadPlatforms(p:any){const id=Number(p._appId||0);p._platformId=0;if(!id){profilePlatforms[p.id]=[];return}try{profilePlatforms[p.id]=await get(`/admin/api/attachments.php?app_id=${id}`)}catch{profilePlatforms[p.id]=[]}}
async function associate(p:any){if(!p._appId||!p._platformId)return store.notify('请选择应用和附件分类','error');try{await put('/admin/api/mobileconfig.php',{action:'associate',mc_id:p.id,app_id:Number(p._appId),platform_id:Number(p._platformId),version:p._version||'1.0'});store.notify('已关联到应用附件');await load()}catch(e:any){store.notify(e?.message||'关联失败','error')}}

async function saveCert(){try{if(certEditing.value){await put('/admin/api/mobileconfig.php',{action:'update_cert',id:certEditing.value,...certDraft})}else{await post('/admin/api/mobileconfig.php',{action:'create_cert',...certDraft})}resetCert();await load();store.notify('证书已保存')}catch(e:any){store.notify(e?.message||'证书保存失败','error')}}
async function editCert(c:any){try{const d:any=await get(`/admin/api/mobileconfig.php?action=get_cert&id=${c.id}`);certEditing.value=Number(c.id);Object.assign(certDraft,{name:d.name||'',mode:d.mode||'text',cert:d.cert||'',key:'',chain:d.chain||'',payload_org:d.payload_org||'',is_global:Number(d.is_global||0)});store.notify(d.has_key?'私钥已保留在服务器；留空不会清除':'该证书目前没有私钥','info')}catch(e:any){store.notify(e?.message||'证书读取失败','error')}}
async function setGlobal(c:any){try{await put('/admin/api/mobileconfig.php',{action:'update_cert',id:c.id,name:c.name,mode:c.mode,payload_org:c.payload_org||'',is_global:1,cert:'',key:'',chain:''});await load();store.notify('已设为全局默认证书')}catch(e:any){store.notify(e?.message||'设置失败','error')}}
async function importLegacy(){try{await post('/admin/api/mobileconfig.php',{action:'import_global_cert'});await load();store.notify('旧全局证书已导入')}catch(e:any){store.notify(e?.message||'没有可导入的旧证书','error')}}
async function removeCert(c:any){if(!confirm(`删除证书「${c.name}」？被 Mobileconfig 引用时后端会拒绝。`))return;try{await del('/admin/api/mobileconfig.php',{action:'delete_cert',id:c.id});if(certEditing.value===Number(c.id))resetCert();await load();store.notify('证书已删除')}catch(e:any){store.notify(e?.message||'删除失败','error')}}
onMounted(load)
</script>

<template><div>
<div class="page-head"><div><h1>Mobileconfig</h1><p>完整管理 iOS WebClip 配置文件、应用附件关联和签名证书；私钥永远不通过 GET 回传。</p></div><button class="button" @click="load"><RefreshCw :size="14"/>刷新</button></div>
<div class="drawer-tabs" style="width:max-content;margin-bottom:13px"><button :class="{active:tab==='profiles'}" @click="tab='profiles'">配置文件</button><button :class="{active:tab==='certs'}" @click="tab='certs'">签名证书</button></div>

<template v-if="tab==='profiles'">
<div class="two-col" style="grid-template-columns:350px minmax(0,1fr)">
<section class="form-card"><div class="form-section"><div class="task-head"><h3><FileKey2 :size="13" style="display:inline;vertical-align:-2px;margin-right:5px"/>{{profileEditing?'编辑配置文件':'生成配置文件'}}</h3><button v-if="profileEditing" class="icon-button" @click="resetProfile"><X :size="13"/></button></div><p>编辑现有记录时会先成功生成新文件，再删除旧文件，避免失败造成文件丢失。</p><div class="field"><label>显示名称</label><input v-model="form.display_name" class="input"></div><div class="field" style="margin-top:9px"><label>目标 URL</label><input v-model="form.target_url" class="input"></div><div class="field" style="margin-top:9px"><label>Bundle ID</label><input v-model="form.bundle_id" class="input"></div><div class="form-grid" style="margin-top:9px"><div class="field"><label>版本</label><input v-model="form.version" class="input"></div><div class="field"><label>安装页模板</label><select v-model="form.template" class="select"><option value="modern">modern</option><option value="classic">classic</option><option value="minimal">minimal</option></select></div></div><div class="field" style="margin-top:9px"><label>签名证书</label><select v-model.number="form.cert_id" class="select"><option :value="0">使用全局证书 / 不签名</option><option v-for="c in certs" :key="c.id" :value="Number(c.id)">{{c.name}}</option></select></div><div class="field" style="margin-top:9px"><label>Payload Organization</label><input v-model="form.payload_org" class="input"></div><div class="field" style="margin-top:9px"><label>说明</label><textarea v-model="form.description" class="textarea"></textarea></div><div class="field" style="margin-top:9px"><label>WebClip 图标</label><div class="page-actions"><label class="button small"><Upload :size="12"/>读取图片为 Icon Data<input type="file" accept="image/*" hidden @change="iconFile(($event.target as HTMLInputElement).files?.[0])"></label><button v-if="form.icon_data" class="button small" @click="form.icon_data=''">清除图标</button></div><small>{{form.icon_data?'已载入 Base64 图标数据':'未设置图标数据'}}</small></div><label class="check-row" style="margin-top:9px"><input v-model="form.fullscreen" type="checkbox">全屏 WebClip</label><button class="button primary" style="width:100%;margin-top:12px" :disabled="generating" @click="saveProfile"><Save :size="13"/>{{generating?'正在生成…':(profileEditing?'重新生成并保存':'生成 Mobileconfig')}}</button></div></section>

<section class="panel"><div class="panel-head"><div><h3>已生成配置文件</h3><span>{{profiles.length}} 个</span></div></div><div class="task-list" style="padding:12px"><article v-for="p in profiles" :key="p.id" class="task-card"><div class="task-head"><div><b>{{p.display_name}}</b><span class="subtle" style="display:block;margin-top:2px">{{p.target_url}}</span></div><span class="badge" :class="{muted:!p.cert_id}">{{p.cert_name||'未签名'}}</span></div><div class="status-grid" style="margin-top:8px"><div class="status-card"><b>版本</b><p>{{p.version}}</p></div><div class="status-card"><b>文件</b><p>{{p.file_size||'—'}}</p></div><div class="status-card"><b>关联应用</b><p>{{p.linked_app_name||'未关联'}}</p></div></div><code style="display:block;margin-top:8px;word-break:break-all">{{p.file_path}}</code><div class="page-actions" style="margin-top:9px"><button class="button small" @click="editProfile(p)"><Pencil :size="12"/>编辑</button><button class="button small" @click="renameProfile(p)">重命名文件</button><a v-if="p.file_path" :href="'/' + String(p.file_path).replace(/^\//,'')" target="_blank" class="button small"><ExternalLink :size="12"/>打开</a><button class="button small danger" @click="removeProfile(p)"><Trash2 :size="12"/>删除</button></div><div class="form-grid" style="margin-top:10px"><div class="field"><label>关联应用</label><select v-model.number="p._appId" class="select" @change="loadPlatforms(p)"><option :value="0">请选择</option><option v-for="a in apps" :key="a.id" :value="Number(a.id)">{{a.name}}</option></select></div><div class="field"><label>附件分类</label><select v-model.number="p._platformId" class="select"><option :value="0">请选择</option><option v-for="pl in (profilePlatforms[p.id]||[])" :key="pl.id" :value="Number(pl.id)">{{pl.name}}</option></select></div><div class="field"><label>附件版本</label><input v-model="p._version" class="input"></div><div class="field" style="align-self:end"><button class="button" style="width:100%" @click="associate(p)"><Link2 :size="12"/>写入附件库</button></div></div></article><div v-if="!profiles.length" class="empty-state">暂无配置文件。</div></div></section>
</div>
</template>

<template v-else>
<div class="two-col" style="grid-template-columns:400px minmax(0,1fr)">
<section class="form-card"><div class="form-section"><div class="task-head"><h3>{{certEditing?'编辑签名证书':'新增签名证书'}}</h3><button v-if="certEditing" class="icon-button" @click="resetCert"><X :size="13"/></button></div><p>编辑时私钥留空表示保留服务器原值，不会把旧私钥回传到浏览器。</p><div class="field"><label>名称</label><input v-model="certDraft.name" class="input"></div><div class="field" style="margin-top:9px"><label>模式</label><select v-model="certDraft.mode" class="select"><option value="text">PEM 文本</option><option value="path">服务器路径</option><option value="upload">已上传文件路径</option></select></div><div class="field" style="margin-top:9px"><label>证书 / 路径</label><textarea v-model="certDraft.cert" class="textarea" style="min-height:120px"></textarea></div><div class="field" style="margin-top:9px"><label>私钥 / 路径</label><textarea v-model="certDraft.key" class="textarea" style="min-height:110px" :placeholder="certEditing?'留空保留原私钥':''"></textarea></div><div class="field" style="margin-top:9px"><label>证书链（可选）</label><textarea v-model="certDraft.chain" class="textarea"></textarea></div><div class="field" style="margin-top:9px"><label>Payload Organization</label><input v-model="certDraft.payload_org" class="input"></div><label class="check-row" style="margin-top:9px"><input v-model="certDraft.is_global" type="checkbox" :true-value="1" :false-value="0">设为全局默认</label><button class="button primary" style="margin-top:12px" @click="saveCert"><Save :size="13"/>{{certEditing?'保存证书修改':'保存新证书'}}</button><button v-if="!certs.some(c=>Number(c.is_global))" class="button" style="margin:12px 0 0 7px" @click="importLegacy">导入旧全局证书</button></div></section>

<section class="panel"><div class="panel-head"><div><h3>证书列表</h3><span>{{certs.length}} 个</span></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>名称</th><th>模式</th><th>状态</th><th>颁发者</th><th>有效期</th><th>操作</th></tr></thead><tbody><tr v-for="c in certs" :key="c.id"><td>{{c.name}}</td><td>{{c.mode}}</td><td><span class="badge" :class="{warning:!c.has_key}">{{c.is_global?'全局 · ':''}}{{c.has_key?'私钥已配置':'缺少私钥'}}</span></td><td>{{c.cert_issuer||'—'}}</td><td>{{c.cert_expires||'—'}}</td><td><div class="page-actions"><button class="button small" @click="editCert(c)"><Pencil :size="12"/>编辑</button><button v-if="!Number(c.is_global)" class="button small" @click="setGlobal(c)">设为默认</button><button class="button small danger" @click="removeCert(c)"><Trash2 :size="12"/>删除</button></div></td></tr><tr v-if="!certs.length"><td colspan="6" class="subtle">暂无证书</td></tr></tbody></table></div></section>
</div>
</template>
</div></template>
