<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { KeyRound, Plus, RefreshCw, Save, Trash2, Upload } from 'lucide-vue-next'
import { del, get, post, put } from '../api'
import { useAppStore } from '../stores/app'
const store=useAppStore();const keys=ref<any[]>([]);const loading=ref(false);const mode=ref<'generate'|'upload'>('generate')
const gen=reactive<any>({name:'AppDown Release',alias:'appdown',store_password:'',key_password:'',validity_years:25,common_name:'AppDown',org_unit:'',org_name:'',locality:'',state_name:'',country:'CN'})
const imp=reactive<any>({name:'',alias:'',store_password:'',key_password:'',file:null})
async function load(){loading.value=true;try{keys.value=await get('/admin/api/keystores.php')}catch(e:any){store.notify(e?.message||'密钥列表加载失败','error')}finally{loading.value=false}}
async function generate(){try{await post('/admin/api/keystores.php?action=generate',gen);Object.assign(gen,{name:'AppDown Release',alias:'appdown',store_password:'',key_password:'',validity_years:25,common_name:'AppDown',org_unit:'',org_name:'',locality:'',state_name:'',country:'CN'});await load();store.notify('JKS 密钥已生成')}catch(e:any){store.notify(e?.message||'生成失败','error')}}
async function upload(){if(!imp.file)return store.notify('请选择 Keystore 文件','error');const fd=new FormData();fd.append('action','upload');fd.append('name',imp.name);fd.append('alias',imp.alias);fd.append('store_password',imp.store_password);fd.append('key_password',imp.key_password);fd.append('file',imp.file);try{await post('/admin/api/keystores.php?action=upload',fd);Object.assign(imp,{name:'',alias:'',store_password:'',key_password:'',file:null});await load();store.notify('Keystore 已导入')}catch(e:any){store.notify(e?.message||'导入失败','error')}}
async function save(k:any){try{await put('/admin/api/keystores.php',{id:k.id,name:k.name,alias:k.alias,org_name:k.org_name||'',org_unit:k.org_unit||'',country:k.country||'',state_name:k.state_name||'',locality:k.locality||'',common_name:k.common_name||'',store_password:k.new_store_password||'',key_password:k.new_key_password||''});k.new_store_password='';k.new_key_password='';store.notify('密钥信息已保存')}catch(e:any){store.notify(e?.message||'保存失败','error')}}
async function remove(k:any){if(!confirm(`确定删除密钥「${k.name}」？已被 APK 使用的密钥后端会拒绝删除。`))return;try{await del('/admin/api/keystores.php',{id:k.id});keys.value=keys.value.filter(x=>x.id!==k.id);store.notify('密钥已删除')}catch(e:any){store.notify(e?.message||'删除失败','error')}}
onMounted(load)
</script>
<template><div>
<div class="page-head"><div><h1>签名密钥</h1><p>创建或导入 Android Keystore。密码继续由 PHP 后端使用 AES-256-GCM 加密保存，不回传明文。</p></div><button class="button" @click="load"><RefreshCw :size="14"/>刷新</button></div>
<div class="drawer-tabs" style="width:max-content;margin-bottom:13px"><button :class="{active:mode==='generate'}" @click="mode='generate'">生成 JKS</button><button :class="{active:mode==='upload'}" @click="mode='upload'">导入 Keystore</button></div>
<section class="form-card" v-if="mode==='generate'"><div class="form-section"><h3><KeyRound :size="13" style="display:inline;vertical-align:-2px;margin-right:5px"/>生成签名密钥</h3><p>服务器需要 JDK / keytool；密码不会出现在命令行参数中。</p><div class="form-grid"><div class="field"><label>名称</label><input v-model="gen.name" class="input"></div><div class="field"><label>Alias</label><input v-model="gen.alias" class="input"></div><div class="field"><label>Keystore 密码</label><input v-model="gen.store_password" type="password" class="input"></div><div class="field"><label>Key 密码</label><input v-model="gen.key_password" type="password" class="input"></div><div class="field"><label>有效期（年）</label><input v-model.number="gen.validity_years" type="number" min="1" max="100" class="input"></div><div class="field"><label>Common Name</label><input v-model="gen.common_name" class="input"></div><div class="field"><label>组织</label><input v-model="gen.org_name" class="input"></div><div class="field"><label>部门</label><input v-model="gen.org_unit" class="input"></div><div class="field"><label>省/州</label><input v-model="gen.state_name" class="input"></div><div class="field"><label>城市</label><input v-model="gen.locality" class="input"></div><div class="field"><label>国家代码</label><input v-model="gen.country" class="input" maxlength="2"></div></div><button class="button primary" style="margin-top:12px" @click="generate"><Plus :size="13"/>生成密钥</button></div></section>
<section class="form-card" v-else><div class="form-section"><h3><Upload :size="13" style="display:inline;vertical-align:-2px;margin-right:5px"/>导入签名密钥</h3><p>JKS/Keystore 会使用 keytool 真解析；P12/PFX 优先由 OpenSSL 校验。</p><div class="form-grid"><div class="field"><label>名称</label><input v-model="imp.name" class="input"></div><div class="field"><label>Alias</label><input v-model="imp.alias" class="input"></div><div class="field"><label>Keystore 密码</label><input v-model="imp.store_password" type="password" class="input"></div><div class="field"><label>Key 密码</label><input v-model="imp.key_password" type="password" class="input"></div><label class="drop-zone full"><Upload :size="22" style="margin:auto"/><b>{{imp.file?.name||'选择 Keystore / JKS / P12 / PFX'}}</b><span>后台会验证密钥库与密码是否真实可用。</span><input type="file" hidden @change="imp.file=($event.target as HTMLInputElement).files?.[0]||null"></label></div><button class="button primary" style="margin-top:12px" @click="upload">导入密钥</button></div></section>
<section class="panel" style="margin-top:13px"><div class="panel-head"><div><h3>已有密钥</h3><span>{{keys.length}} 个</span></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>名称</th><th>Alias</th><th>文件</th><th>加密</th><th>组织</th><th>新密码（可选）</th><th>操作</th></tr></thead><tbody><tr v-for="k in keys" :key="k.id"><td><input v-model="k.name" class="input" style="min-width:150px"></td><td><input v-model="k.alias" class="input" style="min-width:120px"></td><td>{{k.file_url}}</td><td><span class="badge" :class="{warning:!k.encrypted}">{{k.encrypted?'AES 加密':'待迁移'}}</span></td><td><input v-model="k.org_name" class="input" style="min-width:130px"></td><td><div style="display:grid;gap:5px"><input v-model="k.new_store_password" type="password" class="input" placeholder="新 Store 密码"><input v-model="k.new_key_password" type="password" class="input" placeholder="新 Key 密码"></div></td><td><div class="page-actions"><button class="button small" @click="save(k)"><Save :size="12"/>保存</button><button class="button small danger" @click="remove(k)"><Trash2 :size="12"/>删除</button></div></td></tr><tr v-if="!keys.length"><td colspan="7" class="subtle">暂无签名密钥</td></tr></tbody></table></div></section>
</div></template>
