<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, reactive, ref } from 'vue'
import { Play, RefreshCw, RotateCcw, Save, ShieldCheck, TerminalSquare, Trash2 } from '@lucide/vue'
import { get, post } from '../api'
import { useAppStore } from '../stores/app'

const store=useAppStore();const overview=ref<any>({checks:[],info:[],counts:[]});const android=ref<any>(null);const ios=ref<any>(null);const androidLog=ref<any>(null);const iosLog=ref<any>(null);const xcodeLog=ref<any>(null);const busy=ref('');let timer:number|undefined
const env=reactive<Record<string,string>>({custom_java_home:'',custom_android_home:'',custom_ios_ssh_port:'',custom_ios_container:'',custom_docker_data_root:'',custom_docker_mirror:'',custom_docker_osx_image:'',custom_xcode_version:''})
const xcode=reactive({apple_id:'',password:'',code:''})
const xcodeRunning=computed(()=>['installing','downloading','awaiting_2fa'].includes(String(xcodeLog.value?.status||'')))
const waiting2fa=computed(()=>String(xcodeLog.value?.status||'')==='awaiting_2fa')
const labels:Record<string,string>={arch:'CPU 架构',java:'Java 17',android_home:'Android SDK',sdkmanager:'SDK Manager',build_tools:'Build Tools 34',platform:'Android 34',keytool:'Keytool',docker:'Docker',docker_running:'Docker Daemon',kvm:'KVM',container_exists:'macOS 容器',container_running:'容器运行',ssh:'SSH',xcode:'Xcode'}

function statusItems(obj:any){return Object.entries(obj||{}).filter(([k])=>k!=='all_ok').map(([k,v]:any)=>({key:k,label:labels[k]||k,ok:!!v?.ok,detail:v?.version||v?.path||''}))}
async function load(){try{const [ov,set,a,i,al,il,xl]=await Promise.all([get('/admin/api/system-overview.php'),get('/admin/api/settings.php'),get('/admin/api/system.php?action=android_status'),get('/admin/api/system.php?action=ios_status'),get('/admin/api/system.php?action=install_log'),get('/admin/api/system.php?action=ios_install_log'),get('/admin/api/system.php?action=ios_xcode_log')]);overview.value=ov;android.value=a;ios.value=i;androidLog.value=al;iosLog.value=il;xcodeLog.value=xl;Object.keys(env).forEach(k=>env[k]=String(set[k]??''))}catch(e:any){store.notify(e?.message||'系统信息加载失败','error')}}
async function refreshRuntime(){try{const [a,i,al,il,xl]=await Promise.all([get('/admin/api/system.php?action=android_status'),get('/admin/api/system.php?action=ios_status'),get('/admin/api/system.php?action=install_log'),get('/admin/api/system.php?action=ios_install_log'),get('/admin/api/system.php?action=ios_xcode_log')]);android.value=a;ios.value=i;androidLog.value=al;iosLog.value=il;xcodeLog.value=xl}catch{}}
async function action(name:string,label:string,danger=false){if(danger&&!confirm(`确定执行「${label}」？`))return;busy.value=name;try{await post(`/admin/api/system.php?action=${name}`,{});store.notify(`${label} 已启动`,'info');await refreshRuntime()}catch(e:any){store.notify(e?.message||`${label} 失败`,'error')}finally{busy.value=''}}
async function verifyXcode(){busy.value='verify_ios_xcode';try{const r:any=await post('/admin/api/system.php?action=verify_ios_xcode',{});store.notify(r.ok?(r.info||'Xcode 验证通过'):(r.info||'Xcode 尚未就绪'),r.ok?'success':'error');await refreshRuntime()}catch(e:any){store.notify(e?.message||'验证失败','error')}finally{busy.value=''}}
async function saveEnv(){busy.value='save_env_paths';try{await post('/admin/api/system.php?action=save_env_paths',{...env});store.notify('Builder 自定义路径已保存');await refreshRuntime()}catch(e:any){store.notify(e?.message||'保存环境配置失败','error')}finally{busy.value=''}}
async function installXcode(){if(!xcode.apple_id.trim()||!xcode.password)return store.notify('请填写 Apple ID 和密码','error');busy.value='install_ios_xcode';try{await post('/admin/api/system.php?action=install_ios_xcode',{apple_id:xcode.apple_id.trim(),password:xcode.password});xcode.password='';store.notify('Xcode 安装任务已启动，凭据不会保存','info');await refreshRuntime()}catch(e:any){store.notify(e?.message||'启动 Xcode 安装失败','error')}finally{busy.value=''}}
async function submit2fa(){if(!xcode.code.trim())return store.notify('请输入验证码','error');busy.value='submit_ios_2fa';try{await post('/admin/api/system.php?action=submit_ios_2fa',{code:xcode.code.trim()});xcode.code='';store.notify('验证码已提交','info');await refreshRuntime()}catch(e:any){store.notify(e?.message||'验证码提交失败','error')}finally{busy.value=''}}
async function resetStatus(type:'android'|'ios'){const name=type==='android'?'reset_install_status':'reset_ios_install_status';try{await post(`/admin/api/system.php?action=${name}`,{});store.notify('任务状态已重置');await refreshRuntime()}catch(e:any){store.notify(e?.message||'重置失败','error')}}
onMounted(()=>{load();timer=window.setInterval(async()=>{if(androidLog.value?.status==='running'||iosLog.value?.status==='running'||xcodeRunning.value)await refreshRuntime()},2500)});onBeforeUnmount(()=>{if(timer)clearInterval(timer)})
</script>

<template><div>
<div class="page-head"><div><h1>系统信息</h1><p>查看 PHP/SQLite 运行状态，并完整管理 Android、Docker-OSX 与 Xcode 构建环境。</p></div><button class="button" @click="load"><RefreshCw :size="14"/>重新检测</button></div>

<div class="status-grid" style="margin-bottom:13px"><div v-for="c in overview.counts" :key="c.label" class="status-card"><div class="status-line"><b>{{c.label}}</b><span class="badge">{{c.value}}</span></div><p>当前站点 / 租户业务对象</p></div></div>
<div class="two-col" style="margin-bottom:13px">
 <section class="panel"><div class="panel-head"><div><h3>运行环境</h3><span>PHP 与关键扩展</span></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>检测项</th><th>要求</th><th>当前</th><th>状态</th></tr></thead><tbody><tr v-for="c in overview.checks" :key="c.label"><td>{{c.label}}</td><td>{{c.required}}</td><td><code>{{c.current}}</code></td><td><span class="badge" :class="{danger:!c.ok,muted:!c.ok}">{{c.ok?'正常':'检查'}}</span></td></tr></tbody></table></div></section>
 <section class="panel"><div class="panel-head"><div><h3>服务器信息</h3><span>当前 PHP-FPM / CLI 环境可见数据</span></div></div><div class="task-list" style="padding:12px"><div v-for="i in overview.info" :key="i.label" class="task-card"><div class="task-head"><b>{{i.label}}</b><code style="max-width:68%;white-space:normal;word-break:break-all;text-align:right">{{i.value}}</code></div></div></div></section>
</div>

<div class="two-col">
 <section class="panel"><div class="panel-head"><div><h3>Android 构建环境</h3><span>JDK 17 · Android SDK 34 · Keytool</span></div><span class="badge" :class="{danger:android&&!android.all_ok}">{{android?.all_ok?'就绪':'未就绪'}}</span></div><div style="padding:12px"><div class="status-grid"><div v-for="s in statusItems(android)" :key="s.key" class="status-card"><div class="status-line"><b>{{s.label}}</b><span class="status-dot" :class="{ok:s.ok}"></span></div><p>{{s.detail||(s.ok?'可用':'不可用')}}</p></div></div><div class="page-actions" style="margin-top:12px"><button class="button primary" :disabled="!!busy" @click="action('install_android','安装 Android 环境')"><Play :size="13"/>一键安装</button><button class="button" @click="resetStatus('android')"><RotateCcw :size="13"/>重置任务状态</button><button class="button danger" :disabled="!!busy" @click="action('uninstall_android','卸载 Android 环境',true)"><Trash2 :size="13"/>卸载</button></div><div class="log-box" style="margin-top:12px;min-height:120px">{{androidLog?.log||'暂无 Android 环境任务日志'}}</div></div></section>

 <section class="panel"><div class="panel-head"><div><h3>iOS 构建环境</h3><span>x86_64 · KVM · Docker · macOS SSH · Xcode</span></div><span class="badge" :class="{danger:ios&&!ios.all_ok}">{{ios?.all_ok?'就绪':'未就绪'}}</span></div><div style="padding:12px"><div class="status-grid"><div v-for="s in statusItems(ios)" :key="s.key" class="status-card"><div class="status-line"><b>{{s.label}}</b><span class="status-dot" :class="{ok:s.ok}"></span></div><p>{{s.detail||(s.ok?'可用':'不可用')}}</p></div></div><div class="page-actions" style="margin-top:12px"><button class="button primary" :disabled="!!busy" @click="action('install_ios','Phase 1：安装 Docker + macOS 容器')"><Play :size="13"/>安装容器</button><button class="button" :disabled="!!busy" @click="verifyXcode"><TerminalSquare :size="13"/>验证 Xcode</button><button class="button" @click="resetStatus('ios')"><RotateCcw :size="13"/>重置任务状态</button><button class="button danger" :disabled="!!busy" @click="action('uninstall_ios','卸载 iOS 环境',true)"><Trash2 :size="13"/>卸载</button></div><div class="log-box" style="margin-top:12px;min-height:120px">{{iosLog?.log||'暂无 iOS 环境任务日志'}}</div></div></section>
</div>

<section class="form-card" style="margin-top:13px"><div class="form-section"><h3>Builder 自定义路径与镜像</h3><p>留空即自动检测 / 使用项目默认值。服务端会校验绝对路径、SSH 端口、容器名和 Docker 镜像格式。</p><div class="form-grid"><div class="field"><label>JAVA_HOME</label><input v-model="env.custom_java_home" class="input" placeholder="留空自动检测"></div><div class="field"><label>ANDROID_HOME</label><input v-model="env.custom_android_home" class="input" placeholder="/opt/android-sdk"></div><div class="field"><label>Docker 数据目录</label><input v-model="env.custom_docker_data_root" class="input" placeholder="/var/lib/docker"></div><div class="field"><label>Docker 镜像加速</label><input v-model="env.custom_docker_mirror" class="input" placeholder="多个 URL 用逗号分隔"></div><div class="field"><label>Docker-OSX 镜像</label><input v-model="env.custom_docker_osx_image" class="input" placeholder="sickcodes/docker-osx:auto"></div><div class="field"><label>macOS 容器名称</label><input v-model="env.custom_ios_container" class="input" placeholder="ysapp-ios-builder"></div><div class="field"><label>SSH 端口</label><input v-model="env.custom_ios_ssh_port" class="input" placeholder="50922"></div><div class="field"><label>Xcode 版本</label><input v-model="env.custom_xcode_version" class="input" placeholder="留空自动；例如 15.4"><small>Docker-OSX :auto 的 Catalina 留空时会自动选择 Xcode 12.4；较新 macOS 留空使用 latest。</small></div></div><button class="button primary" style="margin-top:10px" :disabled="!!busy" @click="saveEnv"><Save :size="13"/>保存 Builder 配置</button></div></section>

<section class="form-card" style="margin-top:13px"><div class="form-section"><h3>Phase 2：安装 Xcode</h3><p>只有 macOS SSH 已真实就绪时才能启动。Apple ID 和密码只写入 0600 临时文件，Worker 读取后删除；需要 2FA 时会显示验证码输入。Xcode 最终以 xcodebuild 实测结果为准。</p><div class="form-grid"><div class="field"><label>Apple ID</label><input v-model="xcode.apple_id" type="email" class="input" autocomplete="username"></div><div class="field"><label>密码</label><input v-model="xcode.password" type="password" class="input" autocomplete="current-password"></div></div><div class="page-actions" style="margin-top:10px"><button class="button primary" :disabled="!!busy||xcodeRunning" @click="installXcode"><Play :size="13"/>安装 Xcode</button><span class="badge" :class="{warning:xcodeRunning}">{{xcodeLog?.status||'idle'}}</span></div><div v-if="waiting2fa" class="form-grid" style="margin-top:12px"><div class="field"><label>Apple 两步验证码</label><input v-model="xcode.code" class="input" maxlength="6" inputmode="numeric" placeholder="000000"></div><div class="field" style="align-self:end"><button class="button primary" :disabled="!!busy" @click="submit2fa"><ShieldCheck :size="13"/>提交验证码</button></div></div><div class="log-box" style="margin-top:12px;min-height:140px">{{xcodeLog?.log||'暂无 Xcode 安装日志'}}</div></div></section>

<div class="card" style="margin-top:13px"><h3>安全边界</h3><p class="subtle" style="line-height:1.7">Vue 只调用登录 + CSRF 保护的 PHP API；系统命令、临时凭据权限、Builder Worker 和租户上下文仍由服务端控制。SaaS 租户看到的是自己的数据库统计和业务数据，不能通过浏览器参数切换 tenant。</p></div>
</div></template>
