<?php
require_once __DIR__ . '/../includes/init.php';
require_once __DIR__ . '/../includes/layout.php';
require_auth();
admin_header('导入导出', 'backup');
?>
<div class="page-header"><h1>导入导出</h1></div>
<div class="card"><h3>导出数据</h3><p style="color:var(--text-secondary);line-height:1.7">设置密码后生成 <b>.enc 完整备份</b>（AES-256-GCM + Argon2id/PBKDF2），可迁移签名材料；留空密码生成普通 ZIP，并主动省略私钥和 Keystore 密码。勾选“应用数据”会自动带上 APK、IPA、Mobileconfig 的生成/版本历史。</p><div class="backup-grid" id="exportChecks"><label class="check-item"><input type="checkbox" value="site_settings" checked>站点配置</label><label class="check-item"><input type="checkbox" value="apps" checked>应用数据与版本历史</label><label class="check-item"><input type="checkbox" value="app_downloads" checked>下载按钮</label><label class="check-item"><input type="checkbox" value="app_images" checked>应用轮播图</label><label class="check-item"><input type="checkbox" value="feature_categories" checked>特色卡片分类</label><label class="check-item"><input type="checkbox" value="feature_cards" checked>特色卡片</label><label class="check-item"><input type="checkbox" value="friend_links" checked>友情链接</label><label class="check-item"><input type="checkbox" value="custom_code" checked>自定义代码</label><label class="check-item"><input type="checkbox" value="app_platforms" checked>附件平台分类</label><label class="check-item"><input type="checkbox" value="app_attachments" checked>附件记录</label><label class="check-item"><input type="checkbox" value="image_categories" checked>图片库分类</label><label class="check-item"><input type="checkbox" value="image_library" checked>图片库数据</label><label class="check-item"><input type="checkbox" value="admin_users">管理员账户</label></div><label class="check-item backup-uploads"><input type="checkbox" id="exportUploads" checked><b>上传文件目录</b><small>安装包、图片、Mobileconfig 等</small></label><div class="form-row"><div class="form-group"><label>加密密码 <small>推荐，至少 8 位</small></label><input type="password" class="form-control" id="exportPwd" minlength="8" autocomplete="new-password" placeholder="留空则生成不含私钥的 ZIP"></div><div class="form-group"><label>确认密码</label><input type="password" class="form-control" id="exportPwd2" autocomplete="new-password" placeholder="再次输入密码"></div></div><button class="btn btn-primary" id="exportBtn" onclick="doExport()"><i class="fas fa-download"></i> 导出备份</button></div>
<div class="card"><h3>导入数据</h3><p style="color:var(--text-secondary);line-height:1.7">支持 v3 以及旧版 AppDown ZIP/加密备份。先解密预览，再选择恢复内容。<b style="color:var(--danger)">勾选的数据会覆盖对应现有数据。</b></p><div class="form-row"><div class="form-group"><label>备份文件</label><input type="file" class="form-control" id="importFile" accept=".enc,.zip"></div><div class="form-group"><label>解密密码</label><div style="display:flex;gap:8px"><input type="password" class="form-control" id="importPwd" placeholder="无密码 ZIP 留空"><button class="btn btn-outline" id="previewBtn" onclick="previewBackup()">预览</button></div></div></div><div id="previewBox" style="display:none;background:var(--bg);border-radius:8px;padding:14px;margin-bottom:14px"><div class="backup-grid" id="importChecks"></div><label class="check-item backup-uploads" id="importUploadsWrap" style="display:none"><input type="checkbox" id="importUploads" checked><b>恢复上传文件</b><small id="uploadInfo"></small></label><p id="backupMeta" style="font-size:.82em;color:var(--text-secondary)"></p><button class="btn btn-danger" id="importBtn" onclick="doImport()"><i class="fas fa-upload"></i> 导入选中数据</button></div></div>
<div class="card"><h3>备份说明</h3><table style="width:100%;font-size:.9em;line-height:1.7"><tbody><tr><td style="font-weight:600;width:140px;padding:7px 0">完整加密备份</td><td>AES-256-GCM；优先 Argon2id，无 sodium 时使用 PBKDF2-HMAC-SHA256 600,000 次</td></tr><tr><td style="font-weight:600;padding:7px 0">无密码 ZIP</td><td>不包含私钥、Keystore 密码和敏感签名文件</td></tr><tr><td style="font-weight:600;padding:7px 0">兼容性</td><td>继续支持旧版 ZIP、纯 JSON 与旧 AES-GCM 备份</td></tr><tr><td style="font-weight:600;padding:7px 0">安全检查</td><td>导入时检查路径遍历、文件数量、解压大小和异常压缩比</td></tr></tbody></table></div>
<style>.backup-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(210px,1fr));gap:8px;margin:12px 0}.check-item{display:flex;align-items:center;gap:8px;padding:8px 12px;background:var(--bg);border-radius:6px;cursor:pointer;font-size:.9em}.check-item input{accent-color:var(--primary);width:16px;height:16px}.check-item small{color:var(--text-secondary);margin-left:auto}.backup-uploads{margin:10px 0 16px}</style>
<script>
const labels={site_settings:'站点配置',apps:'应用数据',app_downloads:'下载按钮',app_images:'应用轮播图',feature_categories:'特色卡片分类',feature_cards:'特色卡片',friend_links:'友情链接',custom_code:'自定义代码',app_platforms:'附件平台分类',app_attachments:'附件记录',image_categories:'图片库分类',image_library:'图片库数据',admin_users:'管理员账户',keystores:'Android 签名密钥',mc_certificates:'Mobileconfig 签名证书',generated_mobileconfigs:'Mobileconfig 历史',generated_apks:'APK 生成历史',generated_ipas:'IPA 生成历史'};
async function doExport(){const p=document.getElementById('exportPwd').value,p2=document.getElementById('exportPwd2').value,t=[...document.querySelectorAll('#exportChecks input:checked')].map(x=>x.value),u=document.getElementById('exportUploads').checked;if(!t.length&&!u){AlertModal.error('请选择导出内容');return}if(p&&p.length<8){AlertModal.error('加密密码至少8位');return}if(p!==p2){AlertModal.error('两次输入的密码不一致');return}const b=document.getElementById('exportBtn');b.disabled=true;try{const r=await API.postRaw('/admin/api/backup.php',{action:'export',password:p,tables:t,include_uploads:u});if(r.headers.get('Content-Type')?.includes('application/json')){const e=await r.json();AlertModal.error('导出失败',e.error||'未知错误');return}const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=r.headers.get('X-Filename')||(p?'appdown_backup.enc':'appdown_backup.zip');a.click();URL.revokeObjectURL(url);AlertModal.success('导出成功',p?'完整加密备份已下载':'普通 ZIP 已下载；签名私钥和密码未包含')}catch(e){AlertModal.error('导出失败',e.message)}finally{b.disabled=false}}
function addPreviewRow(container,key,count){const row=document.createElement('label');row.className='check-item';const input=document.createElement('input');input.type='checkbox';input.value=key;input.checked=key!=='admin_users';const name=document.createElement('span');name.textContent=(labels[key]||key)+(key==='admin_users'?' ⚠️':'');const n=document.createElement('small');n.textContent=String(count)+' 条';row.append(input,name,n);container.appendChild(row)}
async function previewBackup(){const f=document.getElementById('importFile').files[0],p=document.getElementById('importPwd').value;if(!f){AlertModal.error('请选择备份文件');return}const fd=new FormData();fd.append('action','decrypt_preview');fd.append('file',f);fd.append('password',p);try{const r=await fetch('/admin/api/backup.php',{method:'POST',headers:{'X-CSRF-Token':CSRF_TOKEN,'X-Requested-With':'XMLHttpRequest'},body:fd}),d=await r.json();if(d.error){AlertModal.error('解密失败',d.error);return}const c=document.getElementById('importChecks');c.replaceChildren();for(const [k,n] of Object.entries(d.tables||{}))addPreviewRow(c,k,n);const w=document.getElementById('importUploadsWrap');w.style.display=d.has_uploads?'flex':'none';document.getElementById('uploadInfo').textContent=d.has_uploads?`${d.uploads_count} 个 · ${d.uploads_size}`:'';const m=d.meta||{};document.getElementById('backupMeta').textContent=`备份时间：${m.exported_at||'未知'} · 版本：${m.version||'未知'} · ${m.signing_materials_included?'含签名材料':'不含签名私钥'}`;document.getElementById('previewBox').style.display='block'}catch(e){AlertModal.error('预览失败',e.message)}}
async function doImport(){const f=document.getElementById('importFile').files[0],p=document.getElementById('importPwd').value,t=[...document.querySelectorAll('#importChecks input:checked')].map(x=>x.value),u=document.getElementById('importUploads').checked&&document.getElementById('importUploadsWrap').style.display!=='none';if(!t.length&&!u){AlertModal.error('请选择导入内容');return}if(!await AlertModal.confirm('确定导入吗？','选中的类别会覆盖现有数据，此操作不可逆。',{icon:'warning',okText:'确定导入',okClass:'btn-danger'}))return;const fd=new FormData();fd.append('action','import');fd.append('file',f);fd.append('password',p);fd.append('tables',JSON.stringify(t));fd.append('include_uploads',u?'1':'0');const b=document.getElementById('importBtn');b.disabled=true;try{const r=await fetch('/admin/api/backup.php',{method:'POST',headers:{'X-CSRF-Token':CSRF_TOKEN,'X-Requested-With':'XMLHttpRequest'},body:fd}),d=await r.json();d.error?AlertModal.error('导入失败',d.error):AlertModal.success('导入成功',d.message||'数据已恢复')}catch(e){AlertModal.error('导入失败',e.message)}finally{b.disabled=false}}
</script>
<?php admin_footer(); ?>