#!/usr/bin/env php
<?php
if (php_sapi_name() !== 'cli') { http_response_code(403); exit('CLI only'); }
set_time_limit(0);error_reporting(E_ALL);
require_once __DIR__ . '/../includes/version.php';
if (defined('APPDOWN_EDITION') && APPDOWN_EDITION === 'saas') require_once __DIR__ . '/../includes/saas.php';
require_once __DIR__ . '/../includes/db.php';require_once __DIR__ . '/../includes/helpers.php';require_once __DIR__ . '/../includes/security.php';require_once __DIR__ . '/../includes/upload.php';require_once __DIR__ . '/../includes/template_builder.php';
$taskId=(int)($argv[1]??0);if(!$taskId){fwrite(STDERR,"usage: template-builder-worker.php <task_id>\n");exit(64);} $pdo=get_db();ensure_template_builder_schema($pdo);$job='';
function tb_update(PDO $pdo,int $id,array $fields):void{$parts=[];$values=[];foreach($fields as $k=>$v){$parts[]="$k=?";$values[]=$v;}$parts[]="updated_at=datetime('now')";$values[]=$id;$pdo->prepare('UPDATE build_tasks SET '.implode(',',$parts).' WHERE id=?')->execute($values);}
function tb_fail(PDO $pdo,int $id,string $message):void{tb_update($pdo,$id,['status'=>'failed','error_msg'=>redact_sensitive_text($message),'progress_msg'=>'构建失败']);}
function tb_rm_tree(string $dir):void{if($dir===''||!is_dir($dir))return;$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($dir,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST);foreach($it as $f){$f->isDir()?@rmdir($f->getPathname()):@unlink($f->getPathname());}@rmdir($dir);}
function tb_copy_secret(string $src,string $dst):void{if(!is_file($src)||!copy($src,$dst))throw new RuntimeException('无法准备签名文件');@chmod($dst,0600);}function tb_put_secret(string $value,string $dst):void{if(file_put_contents($dst,$value)===false)throw new RuntimeException('无法准备签名密码');@chmod($dst,0600);}function tb_filesize_label(int $bytes):string{if($bytes>=1048576)return round($bytes/1048576,2).' MB';if($bytes>=1024)return round($bytes/1024,1).' KB';return $bytes.' B';}
try{$stmt=$pdo->prepare("SELECT * FROM build_tasks WHERE id=? AND build_type IN ('template-apk','template-ipa')");$stmt->execute([$taskId]);$task=$stmt->fetch();if(!$task||$task['status']!=='pending')throw new RuntimeException('任务不存在或状态无效');$params=json_decode($task['params'],true)?:[];$platform=$task['build_type']==='template-ipa'?'ios':'android';tb_update($pdo,$taskId,['status'=>'building','progress'=>5,'progress_msg'=>'准备 Template Builder 安全工作区','pid'=>getmypid()]);
$jobsRoot=template_builder_jobs_root();$tenantPrefix='';if(function_exists('current_tenant')&&($tenant=current_tenant(true)))$tenantPrefix=$tenant['slug'].'_';$job=$jobsRoot.'/'.$tenantPrefix.'task_'.$taskId.'_'.bin2hex(random_bytes(5));if(!mkdir($job,0700,true)&&!is_dir($job))throw new RuntimeException('无法创建任务目录');foreach(['input','output','secrets'] as $leaf){if(!mkdir($job.'/'.$leaf,0700,true)&&!is_dir($job.'/'.$leaf))throw new RuntimeException('无法创建任务子目录');}
$templateSrc=template_builder_root().'/builder/templates/'.($platform==='ios'?'ios-webview-template.ipa':'android-webview-template.apk');$templateName=$platform==='ios'?'template.ipa':'template.apk';tb_copy_secret($templateSrc,$job.'/input/'.$templateName);$icon=template_builder_resolve_project_file((string)($params['icon_url']??''));$iconContainer='';if($icon){$ext=strtolower(pathinfo($icon,PATHINFO_EXTENSION))?:'png';$iconFile='icon.'.$ext;tb_copy_secret($icon,$job.'/input/'.$iconFile);$iconContainer='/workspace/input/'.$iconFile;}
$request=['platform'=>$platform,'template'=>'/workspace/input/'.$templateName,'output'=>'/workspace/output/result.'.($platform==='ios'?'ipa':'apk'),'url'=>$params['url'],'app_name'=>$params['app_name'],'version_name'=>$params['version_name']??'1.0.0','version_code'=>(int)($params['version_code']??1),'status_bar_color'=>$params['status_bar_color']??'#000000'];if($iconContainer)$request['icon']=$iconContainer;
if($platform==='android'){$ks=$pdo->prepare('SELECT * FROM keystores WHERE id=?');$ks->execute([(int)($params['keystore_id']??0)]);$row=$ks->fetch();if(!$row)throw new RuntimeException('Android Keystore 不存在');$ksPath=realpath(template_builder_root().'/'.ltrim($row['file_url'],'/'));if(!$ksPath)throw new RuntimeException('Android Keystore 文件不存在');tb_copy_secret($ksPath,$job.'/secrets/signing.jks');tb_put_secret(decrypt_secret((string)$row['store_password']),$job.'/secrets/store.pass');tb_put_secret(decrypt_secret((string)$row['key_password']),$job.'/secrets/key.pass');$request+=['package_name'=>$params['package_name'],'keystore'=>'/run/secrets/signing.jks','keystore_alias'=>$row['alias'],'keystore_password_file'=>'/run/secrets/store.pass','key_password_file'=>'/run/secrets/key.pass','splash_color'=>$params['splash_color']??'#FFFFFF','enable_splash'=>(bool)($params['enable_splash']??true),'splash_duration'=>(int)($params['splash_duration']??1200)];}
else{$idStmt=$pdo->prepare('SELECT * FROM ios_signing_identities WHERE id=?');$idStmt->execute([(int)($params['identity_id']??0)]);$identity=$idStmt->fetch();$pfStmt=$pdo->prepare('SELECT * FROM ios_provisioning_profiles WHERE id=?');$pfStmt->execute([(int)($params['profile_id']??0)]);$profile=$pfStmt->fetch();if(!$identity||!$profile)throw new RuntimeException('Apple 签名材料不存在');if(!template_builder_profile_matches($profile['bundle_pattern'],$params['bundle_id']))throw new RuntimeException('Profile 与 Bundle ID 不匹配');tb_copy_secret($identity['p12_path'],$job.'/secrets/signing.p12');tb_copy_secret($profile['profile_path'],$job.'/secrets/profile.mobileprovision');tb_put_secret(decrypt_secret((string)$identity['p12_password']),$job.'/secrets/p12.pass');$request+=['bundle_id'=>$params['bundle_id'],'p12'=>'/run/secrets/signing.p12','p12_password_file'=>'/run/secrets/p12.pass','mobileprovision'=>'/run/secrets/profile.mobileprovision'];}
file_put_contents($job.'/request.json',json_encode($request,JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES));@chmod($job.'/request.json',0600);tb_update($pdo,$taskId,['progress'=>25,'progress_msg'=>'启动隔离 Template Builder 容器']);$runner=template_builder_runner();$cmd='sudo -n '.escapeshellarg($runner).' build '.escapeshellarg($job).' 2>&1';$out=[];exec($cmd,$out,$code);if($code!==0)throw new RuntimeException("Template Builder 失败 (exit {$code})\n".implode("\n",array_slice($out,-30)));
tb_update($pdo,$taskId,['progress'=>88,'progress_msg'=>'验证并保存构建产物']);$built=$job.'/output/result.'.($platform==='ios'?'ipa':'apk');if(!is_file($built)||filesize($built)<=0)throw new RuntimeException('构建器未产生输出文件');$outDir=template_builder_output_dir($platform);$safe=template_builder_safe_name((string)$params['app_name']);$ver=template_builder_safe_name((string)($params['version_name']??'1.0.0'),'1.0.0');$ext=$platform==='ios'?'ipa':'apk';$filename=resolve_filename_collision($outDir,$safe.'-'.$ver,$ext);$dest=$outDir.'/'.$filename;if(!copy($built,$dest))throw new RuntimeException('无法保存构建结果');@chmod($dest,0644);$url=template_builder_output_url($platform,$filename);$sizeLabel=tb_filesize_label(filesize($dest));
if($platform==='android'){$stmt=$pdo->prepare('INSERT INTO generated_apks (task_id,app_name,package_name,version_name,version_code,url,icon_url,splash_url,apk_url,apk_size,keystore_id) VALUES (?,?,?,?,?,?,?,?,?,?,?)');$stmt->execute([$taskId,$params['app_name'],$params['package_name'],$params['version_name']??'1.0.0',(int)($params['version_code']??1),$params['url'],$params['icon_url']??'','',$url,$sizeLabel,(int)$params['keystore_id']]);}else{$stmt=$pdo->prepare("INSERT INTO generated_ipas (task_id,app_name,bundle_id,version_name,version_code,url,icon_url,ipa_url,ipa_size,signing_mode) VALUES (?,?,?,?,?,?,?,?,?,'signed-template')");$stmt->execute([$taskId,$params['app_name'],$params['bundle_id'],$params['version_name']??'1.0.0',(int)($params['version_code']??1),$params['url'],$params['icon_url']??'',$url,$sizeLabel]);}tb_update($pdo,$taskId,['status'=>'success','progress'=>100,'progress_msg'=>'快速构建与签名完成','result_url'=>$url,'result_size'=>$sizeLabel,'error_msg'=>'']);echo "Template Builder task {$taskId} success: {$url}\n";
}catch(Throwable $e){tb_fail($pdo,$taskId,$e->getMessage());fwrite(STDERR,redact_sensitive_text($e->getMessage())."\n");exit(1);}finally{if($job!=='')tb_rm_tree($job);}
